### ISSUE TITLE
Waveform synthesis

### ISSUE THREAD

**Issue by 190n** [alda-lang/alda#100]
Could you add an instrument that is a sine wave generator?

For example:

``` alda
sine: c d e f g
```

**Comment by daveyarwood** [comment]
Excellent idea -- it's definitely on our to-do list, and one of my primary motivations for creating Alda. (MIDI just ended up being easier to implement, as a first step.) We can track it here in this issue.

The original idea I had was to use [Overtone](http://overtone.github.io), but it depends on Supercollider, which I think would make it difficult to package. A Java-native solution would be better. [Minim](https://github.com/ddf/Minim) might be a good fit -- [some work has been done in making it easier to use without Processing and as a Maven dependency](https://github.com/ddf/Minim/issues/34).

**Comment by daveyarwood** [comment]
[If Alda becomes a cljc project](https://github.com/alda-lang/alda-cljs/issues/2) (compiling to both Clojure and ClojureScript, I think we could move a lot faster with waveform instruments in ClojureScript (via the Web Audio API, which I even have a [little ClojureScript library](http://github.com/daveyarwood/mantra) for already) than we could in Clojure. In general, the types of libraries we have available to us in JavaScript vs. Java seem a lot more advanced. I've even had fleeting thoughts of abandoning Java altogether and just making Alda a ClojureScript project, which could potentially target the browser, the desktop, and maybe even the console via Node (although I'm not sure if you can use the Web Audio API without a browser).

**Comment by daveyarwood** [comment]
> (although I'm not sure if you can use the Web Audio API without a browser).

Apparently you can: https://github.com/sebpiq/node-web-audio-api

**Comment by daveyarwood** [comment]
[JSyn] (http://www.softsynth.com/jsyn) looks promising.

**Comment by daveyarwood** [comment]
Should also have a look at [JSynthLib](http://jsynthlib.sourceforge.net).

**Comment by daveyarwood** [comment]
[Klangmeister](https://ctford.github.io/klangmeister/synthesis)'s `connect->` has a DSL something like what I'm imagining as a way of designing synthesizer instruments in Alda.

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-sound-engine-clj/issues/4.
