### ISSUE TITLE
Consider calling "quantization" something else 

### ISSUE THREAD

**Issue by stellatigre** [alda-lang/alda#103]
I believe that what is now called "quantization" in ALDA should be called something else.
Quantization is already a [widely recognized / used term in digital music creation]
(https://en.wikipedia.org/wiki/Quantization_(music)).

I realize that [MML quantization is where you probably got the term from](https://github.com/alda-lang/alda/issues/14), but i think ALDA should not copy that usage of the term, because it is significantly different than the much more widely accepted meaning of the term in music.

I realize this isn't a technical issue, but i do believe that standards are important & that using terms more in keeping with standard ones will further ALDA's stated goal of "being useful to non-programmers", by reducing the amount of things to get used to when learning this new tool / context for writing.

**Comment by bluebear94** [comment]
What about relative note length?

**Comment by daveyarwood** [comment]
I've thought about this a bit. We're currently planning a 1.0.0 release -- I'm open to the idea of renaming quantization to something else in the process, so that there is a clear point in time where the terminology changes. I'm not particularly against it being called `quantization` though, drawing from MML terminology.

The question is, what else would we call it? `length`? `fluidity`? `connectedness`??

**Comment by crisptrutski** [comment]
Perhaps `legato` or `sustain`?

**Comment by daveyarwood** [comment]
I'm leaning towards `length` on this one.

**Comment by MadcapJake** [comment]
`length` is confusing next to `duration` though.

Just briefly searching on MML syntax, it seems that `length` is used for what alda calls `duration` and `quantize` is used for the same in alda. How about `articulation`, `cutoff`, or `slur`?

**Comment by elyisgreat** [comment]
How about `rl` for Relative Length?

**Comment by daveyarwood** [comment]
Throwing another idea out there: `spacing`, and we would invert it.
`(spacing 0)` would be totally legato, numbers closer to 100 would be
staccato, and the default spacing would be 10.

**Comment by elyisgreat** [comment]
Since we have lots of options, why not put them to a vote?

**Comment by daveyarwood** [comment]
After much deliberation and soul-searching, I've decided to leave the name `quantization` be, at least for the time being. While I agree that calling it "quantization" is potentially confusing (especially for those familiar with quantizing a sample in a DAW, for instance), the bottom line is that none of the terms proposed so far feel 100% "right" to me, and renaming a core feature of Alda is a big deal, so I feel that if we are going to rename it, the new term should be something that feels undeniably appropriate.

Some key reasons that I'd like to keep it `quantization` for now:
- There doesn't seem to be any "official" term for this concept in music theory, which is interesting. I imagine that the creators of MML had to invent their own term, hence the somewhat quirky term "quantization." At the moment, I feel like "quantization" (in the MML sense) is the best term we have available to describe what this attribute does in Alda. If there were an official term that describes to a tee this concept, I would be a lot more willing to change Alda's term to that.
- I don't foresee Alda ever having something like quantization in the DAW sense, but if we ever do need to name a function that does something like that, we could always call it `align`, `align-to-beat`, `align-notes`, or something to that effect.
- MML musicians will find the term "quantization" familiar.
- @MadcapJake made a good point in #alda: "Personally I don't think it's terribly confusing as you wouldn't know to use the attribute without reading the docs and I don't see how you'd think that it would align a series of notes without including them in some way."

I will remain open to the possibility of renaming (or at least aliasing) `quantization` to something more fitting/intuitive, but I'm going to have to be a little picky about the name we choose, for the reasons outlined above.

Closing this issue for now, but please continue to post ideas for better names, if you have them -- if I'm totally sold on one of them, I'll consider using it.

**Comment by elyisgreat** [comment]
Apparently music theory calls the concept [articulation](https://en.wikipedia.org/wiki/Articulation_(music)). Not sure how that could be formatted (`art` maybe?) though.
