### ISSUE TITLE
[alda "0.10.0"] / [alda "0.10.1"]  - Wrong number of args (3) passed to: lisp/quant

### ISSUE THREAD

**Issue by VitoVan** [alda-lang/alda#116]
~ $ echo "bassoon: o2 d8 e (quant 30, vol 65) f+ g (quant 99) a2" > test.alda
 ~ $ alda play -f test.alda 
```
 clojure.lang.ExceptionInfo: Wrong number of args (3) passed to: lisp/quant
    data: {:file "/tmp/boot.user8423427377577345097.clj", :line 23}
clojure.lang.ArityException: Wrong number of args (3) passed to: lisp/quant
                 ...                                        
  boot.user/eval7489  boot.user8423427377577345097.clj:   23
                 ...                                        
   clojure.core/eval                          core.clj: 3081
alda.cli/eval7333/fn                           cli.clj:   68
                 ...                                        
  clojure.core/apply                          core.clj:  630
   alda.cli/delegate                           cli.clj:  109
      alda.cli/-main                           cli.clj:  122
                 ...                                        
  clojure.core/apply                          core.clj:  630
     boot.user/-main  boot.user8423427377577345097.clj:   19
                 ...                                        
  boot.user/eval7420  boot.user8423427377577345097.clj:   23
                 ...                                        
  boot.main/-main/fn                          main.clj:  161
     boot.main/-main                          main.clj:  161
                 ...                                        
    boot.App.runBoot                          App.java:  242
       boot.App.main                          App.java:  356
```

[alda "0.9.0"] works fine.

**Comment by crisptrutski** [comment]
Hello again :wave: :smile: 

This breakage is intentional I'm afraid - the use of commas to set multiple attributes in a single form has been removed. There's a nice explanation in the [changelog](https://github.com/alda-lang/alda/blob/79e8415767b2780cc26cd3e40e008488b8c60664/CHANGELOG.md#breaking-changes), but the gist is to use `"bassoon: o2 d8 e (quant 30) (vol 65) f+ g (quant 99) a2"` instead.

**Comment by VitoVan** [comment]
@crisptrutski 

Sorry about this, I should read them.

I just followed this page 
http://daveyarwood.github.io/alda/2015/09/05/alda-a-manifesto-and-gentle-introduction/

It's sort of out-date.

**Comment by crisptrutski** [comment]
Just going to tag @daveyarwood here so he can engage on this, guessing that prefacing the blog post or adding some inline edits. Show's him what he gets for writing engaging posts AND pushing the language forward quickly :smile:

**Comment by daveyarwood** [comment]
Whoops! Sorry -- it's on my TODO list to update the blog post -- should be doing that today :)

**Comment by daveyarwood** [comment]
I've updated my introductory blog post. FYI @VitoVan, that should be the only "breaking change" to the examples in my blog post.

**Comment by VitoVan** [comment]
Yeah, it is the only one, thank you.
--
  Sent from my phone.
On Oct 5, 2015 7:08 AM, Dave Yarwood <notifications@github.com> wrote:I've updated my introductory blog post. FYI @VitoVan, that should be the only "breaking change" to the examples in my blog post.
