### ISSUE TITLE
Alda shouldn't be case sensitive

### ISSUE THREAD

**Issue by atrawog** [alda-lang/alda#122]
I started to play around with Alda with my 4 year old son and it's really neat. But it would be great if Alda would support notes & commands written in upper case. Mapping a note to a letter is a challenge by it self. But it becomes a lot harder if you have a keyboard with upper case letters and a screen that shows them lower case. 

So for preschool kids it would be great if **PIANO: C8 D E F G F E D C2** would work in Alda.

**Comment by daveyarwood** [comment]
@atrawog Thanks for your feedback, and I'm glad your son is enjoying Alda!

In general, it's good for us to leave Alda case-sensitive -- it gives us twice the amount of symbols to work with. We might conceivably want to use capital letters for something in the future.

This would be a great use case for our proposed plugin system (#37), though. Once that's implemented, it will be possible to make a "pre-K mode" that treats everything like it's lowercase.
