### ISSUE TITLE
Improve CRAM performance

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda#123]
See: #117, #9

**Comment by daveyarwood** [comment]
(I guess you can't assign multiple people to an issue!)

**Comment by daveyarwood** [comment]
Thinking out loud:

Calculating `*time-scaling*` is slightly complicated in that we have to look at the number on the end of the cram (the easy part) as well as the total would-be duration of the stuff inside (the hard part). Right now we're doing it by doing a dry-run of the events and subtracting the final `current-offset` from the starting offset. Also, I think we just need to calculate the number of beats at this stage.

We could speed this up by just getting a running tally of the "total beats." This will involve hacking into `alda.lisp` a little, but we could add a dynamic var called `*beats-tally*`, which can either be nil (in which case we are not tallying beats, and events are actually created when they're evaluated), or a number of beats (in which case we are in "tally mode," and instead of creating events, we're just adding to the tally). `calc-duration` could bind `*beats-tally*` to 0, evaluate the body, then bind `*beats-tally*` back to nil and return the tally of beats.

**Comment by daveyarwood** [comment]
I'm starting to get something working... WIP commit with planning notes: https://github.com/alda-lang/alda/commit/638b8d3ae4a0ee5df67450ed3382a1236a7583fd 

Still much work to do, but I think the algorithm is probably sound. Not really sure how this will handle nested crams yet, will cross that bridge when I get to it :stuck_out_tongue:

**Comment by daveyarwood** [comment]
Note to self: should improve this code -- can rework `note` et al a bit, making the beat-tallying happen outside of the context of any particular instrument. We do need some way of keeping track of note length values like we do with instruments... maybe some kind of dummy instrument to use for beat-tallying?

**Comment by daveyarwood** [comment]
My latest PR #127 attempted to improve performance, but didn't end up helping really at all. One key insight was that it seems that nesting crams beyond 2 or 3 levels is what seems to be causing the biggest bottleneck. I think performance is OK otherwise. I think we could potentially close this issue for now, and "cross that bridge when we get there" if users run into any major problems with scores using a lot of cram-nesting. Thoughts @crisptrutski ?

**Comment by crisptrutski** [comment]
I think it should be possible to do much better for nested cases still. We should be able to get out of factorial-land still, but not sure when I'll have the time to take a whack. Essentially we need to be able to reuse evaluation, rather than having an "alternate evaluation" mode. Think that functional purity in alda.lisp, and perhaps some memoization could save the day.

Feel free to close, totally a nice to have

**Comment by daveyarwood** [comment]
@crisptrutski I'm generally all for functional purity, although it may be tricky to refactor alda.lisp to be functionally pure without losing the ability to use it in alda.now-ish contexts, i.e. editing scores in real-time in a REPL.

Hmm.... come to think of it, maybe it wouldn't be so hard. We could have all the functions take a score and return a score, and our "score object" would also include all the working context information, like the current instruments. I'd love to clean up alda.lisp, at any rate. I think what I'll do is close this issue and move this conversation to issue #18 (Clean up/refactor code), something I've been meaning to take a look at for a while. Maybe once alda.lisp is taking a more "functional" approach, we can re-open and revisit the issue of cram performance.
