### ISSUE TITLE
Bug re: nesting crams?

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda#124]
@crisptrutski It sounds like there is a bug with nested crams. Looking at:

```
{c {e g}}4
```

I would expect this to sound like `c8 e16 g`, but it sounds like `c8 e g` for some reason. Maybe a note duration didn't get reset somewhere?

**Comment by daveyarwood** [comment]
`{c8 {e g}8}4` sounds right, I think

**Comment by crisptrutski** [comment]
@daveyarwood very strange - nesting sounded correct to me in that benchmark-style file, will investigate this weekend - assuming you haven't rewritten the code by then :smile:

**Comment by daveyarwood** [comment]
True, my rewritten version might incidentally solve this issue :stuck_out_tongue:
