### ISSUE TITLE
Add Repeat Until function

### ISSUE THREAD

**Issue by MillerMark** [alda-lang/alda#126]
Repeat Until allows you to repeat a sequence or a variable holding a note sequence until a particular marker or time is reached. It looks something like this:

```
# repeats until the lastNote marker is reached:
repeat [o4 a4 b c] until %lastNote

# repeats for 30 beats:
repeat [o4 a4 b c] until 30

# repeats for 500 milliseconds:
repeat [o4 a4 b c] until 500ms
```

The sequence would be repeated until the specified time marker is reached. If the sequence is midway through, that sequence would finish (continue playing until its end). To truncate (immediately stop playing) a sequence when the time marker is reached, we could use the "!" character to indicate a hard stop:

```
# repeats until the lastNote marker is reached:
repeat [o4 a4 b c] until %lastNote!

# repeats for 30 beats:
repeat [o4 a4 b c] until 30!

# repeats for 500 milliseconds:
repeat [o4 a4 b c] until 500ms!
```

**Comment by daveyarwood** [comment]
I like it!

**Comment by daveyarwood** [comment]
@MillerMark I also like your idea of a built-in `@endOfScore` marker, which would allow us to repeat musical phrases until the end of a score.

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-core/issues/5.
