### ISSUE TITLE
Chords with more than 6 notes in them do not play properly

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#134]
I've found from playing with the REPL and from running written code that any chord with 7 or more notes in it does not play correctly. Some of the notes, decided at random, will play at the incorrect time, 1 beat after the other notes. You can test this by using the code `piano: o3 c/e/g/>c/e/g/>c`. One of the notes, chosen at random, will not play at the correct time. The more notes you add, the more notes will play incorrectly. For example, the code `piano: o3 c/c+/d/d+/e/f/f+/g/g+/a/a+/b/>c` will play the notes in three different beats, in groups of 6, chosen at random. I'm guessing this is unintended as which note plays out-of-sync is random.

**Comment by daveyarwood** [comment]
Weird! Thanks for reporting this... it was only a matter of time before someone put Alda under some good stress testing :)

This is an interesting bug, and I think it may vary from system to system, as your first example plays as expected for me, and the second example does play a couple of the notes exactly one beat late, and which 2(?) notes in the chord play late each time sounds random, but the notes are divided over only 2 beats, not 3 like you experienced.

It appears that, at least for me, I can only start up to 10 notes at a time (even across multiple instruments), any more than that and any "overflow notes" will be pushed forward one beat. I'm not sure why 10 notes, and I have absolutely no idea why it is pushing them forward by exactly one beat (even if I change the tempo!). Hmm...

**Comment by daveyarwood** [comment]
This is probably some sort of concurrency bug, where the `note` macro is bumping forward the instrument's current-offset before it can finish scheduling the rest of the notes in the chord. If so, the difference between what I'm hearing and what @elyisgreat is hearing could be chalked up to performance difference between our computers.

**Comment by daveyarwood** [comment]
This issue is fixed for me with the new version of Alda on the master branch, which uses [JSyn](http://www.softsynth.com/jsyn) to schedule events precisely in realtime. The new scheduling system will be available starting with Alda 1.0.0-rc2, which will be released soon.

**Comment by elyisgreat** [comment]
sweet! will test as soon as I get my hands on rc2

**Comment by daveyarwood** [comment]
That would be awesome -- I'll give you a heads up when it's released!

**Comment by daveyarwood** [comment]
@elyisgreat [1.0.0-rc2](https://github.com/alda-lang/alda/releases/tag/1.0.0-rc2) is out now!
