### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#137]
I know it's a silly question, but I'm going to ask it anyway, as updating doesn't seem so straightforward. I'm trying to download 0.12.3, however whenever I run `alda repl` it loads 0.12.2. Is it supposed to automatically update, or do I have to redownload it (reinstalling via `curl https://raw.githubusercontent.com/alda-lang/alda/master/bin/alda -o /usr/local/bin/alda && chmod +x /usr/local/bin/alda` didn't work; it still loaded 0.12.2)?

**Comment by daveyarwood** [comment]
It should be a fully automatic process, though you're not the first person to report that auto-updating has not worked. It seems a little unpredictable, unfortunately. We will be moving away from this in the near future in favor of a more manual update process -- tracking that here: #82 

In the meantime, try this, it may help:

    rm -rf ~/.m2/repository/alda
    alda version

Java/Clojure projects are distributed through a system called [Maven](https://maven.apache.org/what-is-maven.html), and on OS X and Linux the "artifacts" (i.e. software packages) are stored in `~/.m2/repository`. When you run a project that uses a build tool to pull in dependencies from Maven, it will check in this directory to see if you already have them, and if you don't, it will download them for you. So, if you delete the Alda artifact that you have, it will force Alda to re-download the latest version (...although it's supposed to be using the latest version anyway).

I just tried the above and it re-downloaded alda 0.12.3 for me -- should work for you too hopefully.

**Comment by elyisgreat** [comment]
Thanks, it worked ^^ Hopefully updates continue automatically, as 0.12.2 was auto installed for me. Now I know what to do in case of auto update not working, though. Thanks!

**Comment by daveyarwood** [comment]
Great!
