### ISSUE TITLE
:help mechanism doesn't include :quit command

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#138]
title. Took me awhile to figure out how to close the REPL, however I eventually figured out that :quit did the trick. However, it's not mentioned in the :help command

**Comment by daveyarwood** [comment]
That's a good insight. I'll add it :)

For reference, you can quit by typing `quit`, `exit`, `bye`, or any of those prefixed with a colon.

**Comment by elyisgreat** [comment]
Thanks. Don't forget :close either; that was the first one I tried

**Comment by daveyarwood** [comment]
To keep things clean, `:quit` will be the "official" way to quit an Alda REPL session, and the only one we will document in the `:help` list of commands, at least for now.

**Comment by daveyarwood** [comment]
Fixed in 0.12.4, which I deployed just now. Thanks for the issue!
