### ISSUE TITLE
Improve scheduling accuracy

### ISSUE THREAD

**Issue by kirbyfan64** [alda-lang/alda#144]
I noticed `alda.sound.midi.play-note!` uses `Thread/sleep`...

...[which worries me](http://stackoverflow.com/a/14165709/2097780)...

As the link shows, `Thread.sleep` isn't guaranteed to be reliable. Has anyone tried Alda at faster tempos?

**Comment by daveyarwood** [comment]
Timing has generally been pretty good for me, even at fast tempos. That being said, you have a good point about `Thread.sleep` not being reliable. Alda's timing/scheduling system could definitely be improved.

One thing to note is that we're currently using [overtone/at-at](https://github.com/overtone/at-at) for note-scheduling\*, which uses a ScheduledThreadPoolExecutor to schedule events. This is probably a little better than just using `Thread.sleep`, but [it looks like it still may not be the most solid way to schedule events](https://community.oracle.com/thread/1143526). I think that what we want, ideally, is an event-scheduling system based on the system's audio clock -- real-time audio processing, in other words. That would be the only way to get truly accurate timing. After some googling, I haven't found any existing Clojure libraries that do real-time audio processing, but it's certainly possible with Java. [JSyn](http://www.softsynth.com/jsyn) in particular looks highly promising, and as a bonus, we could also use it to create waveform synthesis instruments (#100).

\*though I just realized that we're only using at-at to schedule the *start* of notes, but then using plain ol' `Thread.sleep` to wait for the duration of the note before stopping it. We should fix that, if nothing else.

**Comment by ghoger** [comment]
@daveyarwood I'm glad to find this issue/discussion. I've experienced timing anomalies during playback, too. I dug into the code a bit and found the use of ScheduledThreadPoolExecutor and suspected that that is at least part of the problem. I agree that moving to a more real-time note scheduling mechanism is the way to go.

**Comment by kirbyfan64** [comment]
Honestly, I think you should use a library compatible with MIDI to make exporting easier. To me, that's the primary thing keeping me from using Alda more: my use case depends heavily on MIDI exporting.

**Comment by daveyarwood** [comment]
Using a MIDI library would help for exporting MIDI, but we still need a system in place for reliable scheduling of generic audio events (MIDI or otherwise). Once we have waveform synthesis instruments, etc., it will be possible to write scores that have both MIDI and non-MIDI instruments alongside each other.

BTW @kirbyfan64, I've been thinking about the MIDI export story a little bit, and I think probably what we'll do is make that an alternate mode of use for Alda -- i.e. rather than "playing" a score, you'll be able to "export" it to MIDI, which will give you a .mid file.

**Comment by daveyarwood** [comment]
Alda 1.0.0-rc2 (out soon) will use JSyn to schedule events in realtime, which ought to be a lot more precise.
