### ISSUE TITLE
Gradual attribute changes

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda#179]
Currently, translating things like crescendos (gradually increase volume) and ritardandos (gradually decrease tempo) is cumbersome, as you have to manually adjust the attribute over time, like this:

```
(vol 50) c8 (vol 60) d (vol 70) e (vol 80) f (vol 90) g2
```

It would be nice if we had a way to gradually apply an attribute over an established period of time, maybe something like:

```
(vol>) c8 d e f (<vol 50) g2
```

**Comment by elyisgreat** [comment]
I think the best way to implement this is `(attribute value,duration)`. Value is obvious. Duration tells you over how many beats will the attribute change over. For example:

```
piano: (vol 20) c4 d (vol 100,6) e f g a b > c
```

this would mean change the volume from the current value (20) to 100 over 6 beats.

Of course, any volume call after would override the change. `piano: (vol 20) c4 d (vol 100,6) e f g a b > (vol 20) c` would get louder and then get soft on the last note, before it could get to 100.

Now, not *all* attributes would have this ability, and it might have interesting implication effects regarding tempo, but I think this is the best way to do it.

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-core/issues/13.
