### ISSUE TITLE
"Humanization" filters

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda#181]
From an anonymous comment on my blog post introducing Alda

> - filters to allow applying humanization to fragments (add small random timing deviations, volume fluctuations), or turn straight eights into "swinged" eights

Not sure how feasible this will be to implement, but I'm opening the idea here for discussion, as a start.

**Comment by jimcheetham** [comment]
Many of these new suggestions sound like they should be written as a function call that acts on a set of notes; and of course we would be able to define our own functions too.

So if the parser syntax was fixed to the general case of passing arguments, the same syntax would apply to all these filter ideas.

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-core/issues/15.
