### ISSUE TITLE
Add support for alternative notations (e.g. guitar tabs)

### ISSUE THREAD

**Issue by sdroege** [alda-lang/alda#182]
It'd be great if instead of only allowing notes given by name, one could provide them in alternative notations like guitar tabs. For many people it's a more natural representation for playing music on the guitar, and provides some more information over alternatives (like specifying which string should be used).

**Comment by daveyarwood** [comment]
I agree, this would be awesome for guitarists who are more used to tablature than standard notation.

We're planning on implementing a plugin system (#37) at some point -- this will allow you to define your own syntax features to use in Alda scores. Basically, it will work by translating your score (with special syntax) into an ordinary Alda score, and then evaluating it like usual. I think this plugin system should be the way to implement things like this feature.

I don't think guitar tab notation is something we will support in the language itself, though.

**Comment by daveyarwood** [comment]
Closing this issue since #37 covers this and other use cases for alternate syntax.

I'll be keeping guitar tab notation in the back of my mind as we work towards plugins, though. It would definitely be a killer plug-in!
