### ISSUE TITLE
OSX Installer

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#183]
I made an OSX installer for alda to allow users to install the file with one click. I am deferring the decision of whether or not it should be a regular download on the release page to you, however I will go over some details here: 

No app icon is provided. This is in case you had an app icon in mind. If you do I will gladly implement it.

The `alda` file should be placed inside the installer in the directory `Contents/alda-dir` prior to distribution

The installer automatically deletes itself after use. You can provide a fresh installer for each release, differing only in the relevant file.

I know you want to GUI-ify everything in the future, but for now, I think this is an easy way for mac users to install it.

[Empty installer attached here](https://github.com/alda-lang/alda/files/121016/Alda.Installer.zip)

Let me know what you think!

**Comment by daveyarwood** [comment]
Thanks for putting this together. I'm not sure how I feel about having a GUI installer for a command-line program, though. I'm not totally against it, but I feel like a better approach would be to have a Homebrew recipe, so people can just run `brew install alda` to install it.

Also, I ran into this when I tried running this installer:

<img width="475" alt="screen shot 2016-02-07 at 10 26 09 pm" src="https://cloud.githubusercontent.com/assets/4909079/12877971/2706cf72-cdea-11e5-81c8-ecc887ee5240.png">

**Comment by daveyarwood** [comment]
(Leaving this issue open for discussion for now, but I am leaning against closing it in favor of a Homebrew recipe)

**Comment by elyisgreat** [comment]
That's because you have to have to put the `alda` file inside the directory `/Users/dave/Downloads/Alda Installer.app/alda-dir` . I guess I wasn't clear enough when I stated that above. 
You can find a copy of the installer [here](https://github.com/alda-lang/alda/files/121064/Alda.Installer.zip) that has the file already inserted. the thought was that the latest release of the `alda` file would be put in so that people could just download the installer for that version and it would automatically be installed. 

I get why you might not want a GUI installer for a command line program. If someone is knowledgeable enough to use the command line they probably would have no problem installing it. Personally, I made it because of laziness. It's annoying having to give permission to the file and move it every time a new release comes out. And on your end, you have less to explain, and setting up the installer is trivial.

**Comment by daveyarwood** [comment]
Oh, whoops -- I totally missed that part, hah :)  Yeah, that makes sense to me. We would include the latest Alda executable in each install bundle.

I definitely see the value in having a simpler install process like this -- I just think it would be better to focus on creating an easier way to install Alda on the command line.

There are a couple ways we can do this:

1) Maintain packages for package managers, i.e. Homebrew for OS X, Debian/RPM/etc. packages in the repositories for different Linux distributions, I guess NuGet for Windows?

2) We were talking about implementing an `alda update` command in #82. Users would need to install Alda manually the first time, but then they could just run `alda update` whenever they want to update Alda.

I think it would make sense to implement both of these. That would give people the option to manage their Alda versions manually or via their package manager.

I realize it's a bit of a pain to have to update Alda manually every time we release a new version. Sorry about that! It's definitely something I want to get sorted out by the time we release version 1.0.0.
