### ISSUE TITLE
bug in Alda repeat syntax

### ISSUE THREAD

**Issue by heikkil** [alda-lang/alda#187]
Looks like you can not write two open square brackets only separated by whitespace. This is most probably a bug in syntax parser rather than an intended feature.

This results an error:

    [ [c16 d] [e f] ]*4
    16-Feb-21 20:07:23 bala ERROR [alda.repl.core] - Invalid Alda syntax.

But this does not:

    [ e1ms [c16 d] [e f] ]*4

It seems that `e1ms` can be replaced with any valid non-whitespace character(s).
Multipliers (syntax: *n) can be added after any closed bracket without a change in this behaviour.

Running alda v1.0.0-rc8 repl under OS X.

**Comment by daveyarwood** [comment]
Good catch! That does look like a parser bug. I'll dig into this when I get
a chance. Thanks for reporting.

**Comment by daveyarwood** [comment]
Fixed in 1.0.0-rc9.
