### ISSUE TITLE
Misleading update prompt

### ISSUE THREAD

**Issue by heikkil** [alda-lang/alda#188]
The prompt has a capital Y indicating that it is the default value.
However, the y needs to be entered for the update to happen. I'd say
do what the prompt says.

    $ alda update
    Install alda '1.0.0-rc9' over '1.0.0-rc8' ? [Yn]:
    Quitting...
    $ alda update
    Install alda '1.0.0-rc9' over '1.0.0-rc8' ? [Yn]: y
    Attempting download from 'https://github.com/alda-lang/alda/releases/download/1.0.0-rc9/alda'...
    Updated alda 1.0.0-rc8=> 1.0.0-rc9
    If you have any currently running servers, you may want to restart them so that they are running the latest version.

**Comment by jgkamat** [comment]
Whoops, this is my bad, the prompt should be `[yN]`. +1

**Comment by heikkil** [comment]
Thanks. Pull request in  #189.

**Comment by daveyarwood** [comment]
Merged. Thanks!
