### ISSUE TITLE
Capture Ctrl-C in alda repl

### ISSUE THREAD

**Issue by heikkil** [alda-lang/alda#190]
Please capture Crtl-C in alda repl and kill the playback of the current score, instead. It is quite annoying when I try to stop the playing and have to restart the repl. ":quit" and Ctrl-D" should be enough to stop the repl.

I understand that capturing Ctrl-C in Java command line programs is not easy, but [clojure repl can do it](https://github.com/clojure/clojure/blob/master/src/clj/clojure/repl.clj#L255).

**Comment by daveyarwood** [comment]
I like that idea. We'll have to implement the pausing/stopping behavior first (#69) so that playback can be explicitly paused or stopped via `:pause` and `:stop` commands, but I think capturing Ctrl-C as a shortcut to `:stop` would be a nice convenience.

**Comment by heikkil** [comment]
I feel that Ctrl-C should control the whole play/pause/resume cycle:

If there is playback going on, make Ctrl-C print out these options, and then act on the selection:

    ^C: pause playback
    ^X: stop playback

Back in REPL, if there is a paused playback process, make Ctrl-C call `:resume`.

Logically then, if there is no current playback or paused process, Ctrl-C should call `:play`.

**Comment by daveyarwood** [comment]
I'm on board with that -- good ideas!

**Comment by daveyarwood** [comment]
We are still blocked on #69, and I also think we should wait for #154 before we do this.

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-client-java/issues/3.
