### ISSUE TITLE
Invalid Syntax error when using voices with attributes

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#197]
I was loading a score into the repl with this syntax:

```
midi-synth-voice:

V1: (tempo 240)
V2: (tempo 120)
```

Now, when I entered those lines into the repl manually, there was no problem. However when I loaded a score in with those lines, I got this error:

```
Parse error at line 2, column 1:
V2: ⚙clj-expr87766⚙
^
Expected one of:
"*"
"{"
"["
"|"
"@"
"%"
"⚙"
"<"
">"
"o"
"r"
#"[a-g]"

File load aborted.
```

What's going on?

EDIT: Moved the issue with the vertical bars to #196

**Comment by jgkamat** [comment]
I think I've seen this before. Can you try:
```
midi-synth-voice "myvoice":

V1: g4 r2. | >e4 d8 c4 d4. | <b4. r a-4 | >e4 d c< b8 | > c8~2..< g|
V2: [o3 r4. (quant 50) g4. g8 r8|]*2 [o3 r4. (quant 50) g4. g8 r8|]*2
```

That seemed to work when I last had this problem.

**Comment by elyisgreat** [comment]
didn't seem to work.

**Comment by daveyarwood** [comment]
There are two issues here:

1. Voices are not currently correctly handled by the REPL, if you put them on separate lines. See issue #29. TL;DR: each line is considered a separate voice group containing one voice. The REPL is not smart enough to know that you are continuing the same voice group and not starting a new one. I think the work I'm doing on rewriting alda.lisp (#153) will fix this.

2. There appears to be a parsing bug if you have two voices on the same line, and the first voice ends with a Clojure expression (like an attribute change) followed by whitespace.

    This parses OK:

        V1: a (tempo 120)V2: (tempo 240) c

    But this fails to parse (note the space before `V2`):

        V1: a (tempo 120) V2: (tempo 240) c

**Comment by daveyarwood** [comment]
Fixed in [1.0.0-rc11](https://github.com/alda-lang/alda/releases/tag/1.0.0-rc11).

**Comment by elyisgreat** [comment]
By the way, how to attributes work when voices are started and ended?

**Comment by daveyarwood** [comment]
If you can imagine the instrument splitting off into clones of itself, that's sort of what's happening. Each voice has its own parallel timeline, where the instrument has a separate set of attributes -- each voice can be in a different octave, have a different tempo, be at a different volume, etc.

When the voice group ends, whichever voice is further along in the score becomes "voice zero," or the single voice represented by that instrument. In other words, that voice (with all of its attributes) sort of "becomes the instrument" and the other voices disappear.
