### ISSUE TITLE
r/alda

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#198]
As more people start to use Alda, I think that it would be very beneficial to have a place where people could as questions and discuss the language without having to make issues on GitHub. I was browsing Reddit and found that [r/alda](https://www.reddit.com/r/alda) is available for creating a subreddit. I wanted to create it, but I have hesitated in case you wanted to. I think it's a beneficial tool that could help the language grow and connect with its users, and highly recommend creating it. While we're at it we can always discuss it here...

**Comment by daveyarwood** [comment]
That's a great idea! I'm creating /r/alda now. I'll make you an admin/mod -- feel free to edit the sidebar or do whatever else you'd like with the subreddit. What's your reddit username?

**Comment by elyisgreat** [comment]
u/elyisgreat

**Comment by daveyarwood** [comment]
Done. I'll add a link to the README as well.
