### ISSUE TITLE
REPL quit command bug

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#204]
`:quit` command (and their variants) don't check any other text after the command. `:quit`, `:quite`, and `:quitting is not the answer` all quit the REPL. 

This doesn't seem to happen with other commands. `:play` plays the current score but `:player` does not.

Tbh this isn't a crucial bug (I find it funny) but it is a bit strange.

**Comment by daveyarwood** [comment]
Heh, thanks for pointing this out. I just made a commit on master fixing this -- the change will go out in the next release.
