### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by loganherr** [alda-lang/alda#206]
I try to start the server running the command:
  alda start
the response it gives is:
  starting alda server...
  server down

This is off a fresh install on a Mac.  Any clues as to why it's happening? Is there any info I could provide that would help?

The repl still works

**Comment by daveyarwood** [comment]
Hi @loganherr -- there are a couple things we can try to see what's going on.

Try starting the server in the foreground by running `alda server` -- do you get an error message?

**Comment by loganherr** [comment]
It says Address already in use

**Comment by daveyarwood** [comment]
Ah, OK. So I think what may have happened is, the server actually started when you ran `alda start`, but there was a miscommunication between the server and the client, where the client thought the server didn't start.

What is the output of `alda status`?

**Comment by loganherr** [comment]
Status down

**Comment by daveyarwood** [comment]
Alright. How about `ps aux | grep alda` ?

**Comment by loganherr** [comment]
there are two listed at 21581 and 25810
the first is a fingerprint server, the second is grep alda

**Comment by daveyarwood** [comment]
Alright -- so the process running on 21581 is an Alda server. The `--alda-fingerprint` thing is something we include in the command so that the `alda list` command can identify an Alda server. So if you run `alda list`, you should see a server running on port 21581. Does it say "Server up"?

**Comment by loganherr** [comment]
no, it still says down...there any way to stop those two processes?

**Comment by daveyarwood** [comment]
Yeah, that's what I would try at this point.

Now that I think of it, 21581 is probably not the port, but rather the Unix process id (pid). When you run `ps aux | grep alda`, you should see output that looks like this:

```
dave            28938   2.5  4.6  8320780 765344 s003  S     1:21PM   0:48.64 java -Dclojure.compiler.direct-linking=true -jar /usr/local/bin/alda --host http://localhost --port 27713 --pre-buffer 0 --post-buffer 1000 --alda-fingerprint server
dave            29017   0.0  0.0  2432784    636 s003  S+    1:24PM   0:00.00 grep alda
```

The first number on each line is the process id. You can then kill the process by running `kill 28938` (replace 28938 here with the process id on your system)

**Comment by daveyarwood** [comment]
Before you start the server again, check to see if there is already a process running on the default port that Alda uses (port 27713):

```
sudo lsof -i :27713
```

Let me know what that returns.

**Comment by loganherr** [comment]
Yep, killing the process was the fix. Thanks!

It may have been something specific to my machine and network that caused it, I'll let you know if I can replicate it again.

**Comment by daveyarwood** [comment]
OK, please do. Glad we were able to get it working!
