### ISSUE TITLE
Improving song loading time

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#208]
I know you've [talked about the starting time before](https://github.com/alda-lang/alda/issues/74), however I think that it pertained more to when using commands, not in the REPL. I've noticed that for longer scores (>2 minutes), it can take several seconds to load it in, and a few more between when the `:play` command is run and when the song actually plays (This happens with `alda play` as well). I think improving the loading time would greatly improve writing productivity. Of course, this is no easy task, as this could be a huge parser issue. So here  I leave the issue open.

**Comment by daveyarwood** [comment]
Parsing is the bottleneck. I was talking to one of my coworkers, and he pointed out that the issue could be ambiguity in the parser. I think that's probably the case. Going through and trying to eliminate any ambiguity in the parser could help a lot.

**Comment by daveyarwood** [comment]
@elyisgreat Whenever you have a minute, give alda 1.0.0-rc19 a try, and let me know your thoughts. This release features some significant parser improvements, making loading time faster. There is still more we could do, but I think we are off to a good start for now.

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-core/issues/18.
