### ISSUE TITLE
All available syntax 'cheat sheet'...where can I find one?

### ISSUE THREAD

**Issue by lifeluvr** [alda-lang/alda#210]

**Comment by elyisgreat** [comment]
Not a bad thing to have. A good place to start is the [introduction website](http://daveyarwood.github.io/alda/2015/09/05/alda-a-manifesto-and-gentle-introduction); from there you can check out the [docs](https://github.com/alda-lang/alda/tree/master/doc).

**Comment by daveyarwood** [comment]
This is a great idea. A webpage with concise examples, something along the lines of the [Emmet cheat sheet](http://docs.emmet.io/cheat-sheet/), would be ideal. We'll be happy to host it on [alda.io](http://alda.io), should anyone want to take a crack at this. (If you'd like, you can even 

I'll eventually get to this myself if no one else does it first, but I'm pretty busy these days :)

**Comment by lifeluvr** [comment]
Sweet.... Something for me to do!
When contributing for Intel's 'Android Hub'...they prefer things to be submitted using markdown.  Does that work for you?
By the time I'm done writing...I wont need a cheat sheet anymore but, that's really my secret plan....shhhhhh... don't tell ok?

**Comment by daveyarwood** [comment]
I don't have a preference at this point. If you're able to work with the HTML in the [alda.io repo](https://github.com/alda-lang/alda-lang.github.io) and submit pull requests, that would be the best thing, but submitting Markdown documents would be fine too, at least as a starting point until we have a system in place for publishing content to alda.io.

**Comment by lifeluvr** [comment]
10-4 ;)

**Comment by jgkamat** [comment]
Also don't forget about the [new features added](http://daveyarwood.github.io/alda/2015/11/28/alda-has-a-bunch-of-new-features). Once this is finalized, maybe we could put it in ddg, like [this one](https://duckduckgo.com/?q=linux+cheat+sheet&ia=cheatsheet&iax=1).
:smile:

**Comment by daveyarwood** [comment]
I'm working on setting up a basic [Jekyll](http://jekyllrb.com) site -- you can see what I've got so far at http://alda.io.

PRs welcome! I have a (broken) "Cheat Sheet" link in the header that will go to http://alda.io/cheat-sheet. Creating the cheat sheet is now just a matter of putting a file called `cheat-sheet.md` in the root path of the repo. See [about.md](https://github.com/alda-lang/alda-lang.github.io/blob/master/about.md) for an example.

**Comment by jgkamat** [comment]
Damn that's really nice theme! Love the 404 page! :+1:

**Comment by daveyarwood** [comment]
Yeah, I'm diggin it! I may have someone who's handy with CSS style it up a bit at some point and make it more like something uniquely "ours." I think we'll keep the glitchy 404 page though, because it's pretty awesome. :smile:

**Comment by daveyarwood** [comment]
Moving this to https://github.com/alda-lang/alda-lang.github.io/issues/3
