### ISSUE TITLE
Index of available samples..where can I find that?

### ISSUE THREAD

**Issue by lifeluvr** [alda-lang/alda#211]

**Comment by elyisgreat** [comment]
You mean the [List of available instruments](https://github.com/alda-lang/alda/blob/master/doc/list-of-instruments.md)?

**Comment by daveyarwood** [comment]
There are a variety of [examples](https://github.com/alda-lang/alda/tree/master/examples) in this repo.

**Comment by daveyarwood** [comment]
@lifeluvr Does that answer your question?

**Comment by lifeluvr** [comment]
Yes...and then some.... thank you  :) 
I am honored to meet you Mr. Yarwood!
Please allow me to introduce myself...
I'm Eric Payne. a musician/geek and Alda is holding my imagination captive!
It seems I'm powerless to think of much else... even projects I've already started!
I see so many possibilities... I'm feeling overwhelmed at the moment!
One of my burning desires is to see an 'Audacity' plugin for playing .alda files.
Unfortunately...
I'm more of a writer than a programmer... I usually play with blocks... I'm not good at building them yet....If that makes sense? 
Anyhow, here's a record of my recordings...pre-alda....I can't wait for the next chapter!
https://soundcloud.com/ericpayne2/

**Comment by lifeluvr** [comment]
Ok... someone pinch me while I absorb these amazing links!
Ya know... I do have to leave the computer once in while, right?....oh well, I'll get to it tomorrow!

**Comment by daveyarwood** [comment]
Eric, great to meet you! I'm so thrilled that you're as inspired as I am by
this dream of composing music in a text editor. It's actually valuable that
you're not a programmer - I want to make Alda accessible to musicians who
aren't necessarily programmers, so it's good to have input from that end of
the musician/programmer spectrum.

**Comment by lifeluvr** [comment]
My one true hope...
Is to see Alda developed with an evolving assortment of "Front-end" alternatives. Hopefully, one day music once again be apart of EVERY child's education!
The world needs more music and, I think the children need music back in our schools!

**Comment by lifeluvr** [comment]
You've got a fan and advocate for life! I can't wait to see where this goes!
