### ISSUE TITLE
What an honor to be apart of this excitnig time in music evolution!

### ISSUE THREAD

**Issue by lifeluvr** [alda-lang/alda#212]

**Comment by lifeluvr** [comment]
Thank you for being here! I'm working on learning your Github setup. It's a bit different than Intel's Android Hub but, I can't wait to contribute something of substance :)... Maybe, I could write some easy to understand tech articles like I do for Intel?

**Comment by daveyarwood** [comment]
That sounds like it could be beneficial. One area we could really use some
help with is our website-to-be, http://alda.io. The source is in a GitHub
repo, so if you'd like to make any contributions, the most useful way to do
that would be by making pull requests there:
https://github.com/alda-lang/alda-lang.github.io

I'll admit that I haven't thought too much about the public-facing aspect
of the Alda project. Any ideas you have are totally welcome!

**Comment by lifeluvr** [comment]
I'd be honored!
<]8^)

**Comment by daveyarwood** [comment]
:metal:
