### ISSUE TITLE
I can't figure out what symbol to use for repeats or looping simple scores  ":|"

### ISSUE THREAD

**Issue by lifeluvr** [alda-lang/alda#213]
Has this been coded yet? I think it would be an awesome addition to the Cheat Sheet :)

**Comment by jgkamat** [comment]
Have you tried
` piano: o2 [a16b>cdefg]*4`
Yet? The syntax should be `[<part to repeat>]*<number of repeats>`

**Comment by lifeluvr** [comment]
awesome! that's even easier than the syntax I envisioned :)
Thank You jgkamat!

**Comment by jgkamat** [comment]
No problem! Happy to help! :smile:

**Comment by daveyarwood** [comment]
@lifeluvr For reference: https://github.com/alda-lang/alda/blob/master/doc/repeats.md
