### ISSUE TITLE
why move alda.exe to the windows system root?

### ISSUE THREAD

**Issue by Pomax** [alda-lang/alda#217]
This sounds like an incredibly bad idea, instead it would serve people better to explain how to put alda.exe in its own `C:\program files\alda` or similar folder, because `program files` (or `program files (x86)` for 32 bit apps) is where windows programs are supposed to go.

And then if you absolutely need to run it from anywhere (which most windows users won't, because they have no reason to use the command line for anything), explain how to update their PATH, which (again) is the proper way to do things.

And the people that *do* use the command line will be happy to just add another dir to the PATH for the convenience, so trying to get people to copy your executable into the system dir, no matter how you look at it, is not good advice, and worth doing right instead.

**Comment by daveyarwood** [comment]
That's good to know -- I'm pretty clueless about Windows, so I've been slowly piecing together the right instructions for Windows users :)

Putting `alda.exe` in a less system-y folder (like `Program Files\Alda`, I guess) and adding that folder to the `PATH` sounds like the way to go. I haven't a clue how to translate that into instructions for Windows users, though. A Pull Request to update the README would be great!

**Comment by Pomax** [comment]
Always happy to help make a project get cross-platform instructions right. I've filed a PR over on https://github.com/alda-lang/alda/pull/218

**Comment by lifeluvr** [comment]
Hi gang sorry I've been AWOL...
Anyhow, I just got done compiling ADB into a windows app.
For those who don't know... ADB is a set of binaries that enhance your
command line options to communicate with your Android device in debugging
mode.
The binaries have to be installed at the root of c:\ too.. just like Alda!
The app I made is really simple...
It makes a temp file, unpacks the binaries and opens a terminal in that
location.
I can have it delete the temp file or keep it when closed, make a custom
Alda icon and open a terminal with Alda powers!
No installing... touch it and go!
Delete it and it's gone!.. (unless we choose to save the temp file)
I can even have it run a preliminary command for Alda when the terminal
opens!
I'll work on an example right now.
Here's a link for the ADB terminals that don't need ADB installed ;)
WARNING! 'one-touch' download!
http://j.mp/ADB-CMD

On Thu, Apr 14, 2016 at 11:36 AM, Dave Yarwood <notifications@github.com>
wrote:

> Closed #217 <https://github.com/alda-lang/alda/issues/217> via #218
> <https://github.com/alda-lang/alda/pull/218>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/alda-lang/alda/issues/217#event-627812176>
>



-- 
   ***Eric Payne***
   1-619-786-4687
erdapa1@gmail.com
   www.lifeluvr.org

**Comment by lifeluvr** [comment]
About the download: There's 2 apps.One for connected and one for wireless
ADB.

On Sun, Apr 17, 2016 at 3:26 PM, Eric Payne <erdapa1@gmail.com> wrote:

> Hi gang sorry I've been AWOL...
> Anyhow, I just got done compiling ADB into a windows app.
> For those who don't know... ADB is a set of binaries that enhance your
> command line options to communicate with your Android device in debugging
> mode.
> The binaries have to be installed at the root of c:\ too.. just like Alda!
> The app I made is really simple...
> It makes a temp file, unpacks the binaries and opens a terminal in that
> location.
> I can have it delete the temp file or keep it when closed, make a custom
> Alda icon and open a terminal with Alda powers!
> No installing... touch it and go!
> Delete it and it's gone!.. (unless we choose to save the temp file)
> I can even have it run a preliminary command for Alda when the terminal
> opens!
> I'll work on an example right now.
> Here's a link for the ADB terminals that don't need ADB installed ;)
> WARNING! 'one-touch' download!
> http://j.mp/ADB-CMD
>
> On Thu, Apr 14, 2016 at 11:36 AM, Dave Yarwood <notifications@github.com>
> wrote:
>
>> Closed #217 <https://github.com/alda-lang/alda/issues/217> via #218
>> <https://github.com/alda-lang/alda/pull/218>.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/alda-lang/alda/issues/217#event-627812176>
>>
>
>
>
> --
>    ***Eric Payne***
>    1-619-786-4687
> erdapa1@gmail.com
>    www.lifeluvr.org
>



-- 
   ***Eric Payne***
   1-619-786-4687
erdapa1@gmail.com
   www.lifeluvr.org

**Comment by lifeluvr** [comment]
Ok, here it is!
The 'Touch n' Go' Alda Terminal!
Nothing to install!
Run it and a terminal opens up with 'alda repl' already running for you!
https://drive.google.com/open?id=0B3sPmoNzzT_od0dpRzJ2V1JKdHM

On Sun, Apr 17, 2016 at 3:29 PM, Eric Payne <erdapa1@gmail.com> wrote:

> About the download: There's 2 apps.One for connected and one for wireless
> ADB.
>
> On Sun, Apr 17, 2016 at 3:26 PM, Eric Payne <erdapa1@gmail.com> wrote:
>
>> Hi gang sorry I've been AWOL...
>> Anyhow, I just got done compiling ADB into a windows app.
>> For those who don't know... ADB is a set of binaries that enhance your
>> command line options to communicate with your Android device in debugging
>> mode.
>> The binaries have to be installed at the root of c:\ too.. just like Alda!
>> The app I made is really simple...
>> It makes a temp file, unpacks the binaries and opens a terminal in that
>> location.
>> I can have it delete the temp file or keep it when closed, make a custom
>> Alda icon and open a terminal with Alda powers!
>> No installing... touch it and go!
>> Delete it and it's gone!.. (unless we choose to save the temp file)
>> I can even have it run a preliminary command for Alda when the terminal
>> opens!
>> I'll work on an example right now.
>> Here's a link for the ADB terminals that don't need ADB installed ;)
>> WARNING! 'one-touch' download!
>> http://j.mp/ADB-CMD
>>
>> On Thu, Apr 14, 2016 at 11:36 AM, Dave Yarwood <notifications@github.com>
>> wrote:
>>
>>> Closed #217 <https://github.com/alda-lang/alda/issues/217> via #218
>>> <https://github.com/alda-lang/alda/pull/218>.
>>>
>>> —
>>> You are receiving this because you are subscribed to this thread.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/alda-lang/alda/issues/217#event-627812176>
>>>
>>
>>
>>
>> --
>>    ***Eric Payne***
>>    1-619-786-4687
>> erdapa1@gmail.com
>>    www.lifeluvr.org
>>
>
>
>
> --
>    ***Eric Payne***
>    1-619-786-4687
> erdapa1@gmail.com
>    www.lifeluvr.org
>



-- 
   ***Eric Payne***
   1-619-786-4687
erdapa1@gmail.com
   www.lifeluvr.org

**Comment by Pomax** [comment]
Note that on a proper Windows setup, with normal user rights instead of adminstrator user rights, the `C:\` root is a reserved location. As long as UAC is turned on, users cannot touch it without first getting administrator rights. Making things work does not require `adb` to live in the root at all: Android Studio's install that comes with adb puts it in a perfectly normal dir under the Android Studio dir in Program Files, for instance.

**Comment by lifeluvr** [comment]
(HINT: the email above is easily forwarded. If you do that once you'll have
a copy in your 'Sent' email that you can get to whenever you want!)

On Sun, Apr 17, 2016 at 3:54 PM, Eric Payne <erdapa1@gmail.com> wrote:

> Ok, here it is!
> The 'Touch n' Go' Alda Terminal!
> Nothing to install!
> Run it and a terminal opens up with 'alda repl' already running for you!
> https://drive.google.com/open?id=0B3sPmoNzzT_od0dpRzJ2V1JKdHM
>
> On Sun, Apr 17, 2016 at 3:29 PM, Eric Payne <erdapa1@gmail.com> wrote:
>
>> About the download: There's 2 apps.One for connected and one for wireless
>> ADB.
>>
>> On Sun, Apr 17, 2016 at 3:26 PM, Eric Payne <erdapa1@gmail.com> wrote:
>>
>>> Hi gang sorry I've been AWOL...
>>> Anyhow, I just got done compiling ADB into a windows app.
>>> For those who don't know... ADB is a set of binaries that enhance your
>>> command line options to communicate with your Android device in debugging
>>> mode.
>>> The binaries have to be installed at the root of c:\ too.. just like
>>> Alda!
>>> The app I made is really simple...
>>> It makes a temp file, unpacks the binaries and opens a terminal in that
>>> location.
>>> I can have it delete the temp file or keep it when closed, make a custom
>>> Alda icon and open a terminal with Alda powers!
>>> No installing... touch it and go!
>>> Delete it and it's gone!.. (unless we choose to save the temp file)
>>> I can even have it run a preliminary command for Alda when the terminal
>>> opens!
>>> I'll work on an example right now.
>>> Here's a link for the ADB terminals that don't need ADB installed ;)
>>> WARNING! 'one-touch' download!
>>> http://j.mp/ADB-CMD
>>>
>>> On Thu, Apr 14, 2016 at 11:36 AM, Dave Yarwood <notifications@github.com
>>> > wrote:
>>>
>>>> Closed #217 <https://github.com/alda-lang/alda/issues/217> via #218
>>>> <https://github.com/alda-lang/alda/pull/218>.
>>>>
>>>> —
>>>> You are receiving this because you are subscribed to this thread.
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/alda-lang/alda/issues/217#event-627812176>
>>>>
>>>
>>>
>>>
>>> --
>>>    ***Eric Payne***
>>>    1-619-786-4687
>>> erdapa1@gmail.com
>>>    www.lifeluvr.org
>>>
>>
>>
>>
>> --
>>    ***Eric Payne***
>>    1-619-786-4687
>> erdapa1@gmail.com
>>    www.lifeluvr.org
>>
>
>
>
> --
>    ***Eric Payne***
>    1-619-786-4687
> erdapa1@gmail.com
>    www.lifeluvr.org
>



-- 
   ***Eric Payne***
   1-619-786-4687
erdapa1@gmail.com
   www.lifeluvr.org

**Comment by lifeluvr** [comment]
Oh and you don't need any admin rights to run it either ;)


On 4/17/16, Eric Payne <erdapa1@gmail.com> wrote:
> (HINT: the email above is easily forwarded. If you do that once you'll have
> a copy in your 'Sent' email that you can get to whenever you want!)
>
> On Sun, Apr 17, 2016 at 3:54 PM, Eric Payne <erdapa1@gmail.com> wrote:
>
>> Ok, here it is!
>> The 'Touch n' Go' Alda Terminal!
>> Nothing to install!
>> Run it and a terminal opens up with 'alda repl' already running for you!
>> https://drive.google.com/open?id=0B3sPmoNzzT_od0dpRzJ2V1JKdHM
>>
>> On Sun, Apr 17, 2016 at 3:29 PM, Eric Payne <erdapa1@gmail.com> wrote:
>>
>>> About the download: There's 2 apps.One for connected and one for
>>> wireless
>>> ADB.
>>>
>>> On Sun, Apr 17, 2016 at 3:26 PM, Eric Payne <erdapa1@gmail.com> wrote:
>>>
>>>> Hi gang sorry I've been AWOL...
>>>> Anyhow, I just got done compiling ADB into a windows app.
>>>> For those who don't know... ADB is a set of binaries that enhance your
>>>> command line options to communicate with your Android device in
>>>> debugging
>>>> mode.
>>>> The binaries have to be installed at the root of c:\ too.. just like
>>>> Alda!
>>>> The app I made is really simple...
>>>> It makes a temp file, unpacks the binaries and opens a terminal in that
>>>> location.
>>>> I can have it delete the temp file or keep it when closed, make a
>>>> custom
>>>> Alda icon and open a terminal with Alda powers!
>>>> No installing... touch it and go!
>>>> Delete it and it's gone!.. (unless we choose to save the temp file)
>>>> I can even have it run a preliminary command for Alda when the terminal
>>>> opens!
>>>> I'll work on an example right now.
>>>> Here's a link for the ADB terminals that don't need ADB installed ;)
>>>> WARNING! 'one-touch' download!
>>>> http://j.mp/ADB-CMD
>>>>
>>>> On Thu, Apr 14, 2016 at 11:36 AM, Dave Yarwood
>>>> <notifications@github.com
>>>> > wrote:
>>>>
>>>>> Closed #217 <https://github.com/alda-lang/alda/issues/217> via #218
>>>>> <https://github.com/alda-lang/alda/pull/218>.
>>>>>
>>>>> —
>>>>> You are receiving this because you are subscribed to this thread.
>>>>> Reply to this email directly or view it on GitHub
>>>>> <https://github.com/alda-lang/alda/issues/217#event-627812176>
>>>>>
>>>>
>>>>
>>>>
>>>> --
>>>>    ***Eric Payne***
>>>>    1-619-786-4687
>>>> erdapa1@gmail.com
>>>>    www.lifeluvr.org
>>>>
>>>
>>>
>>>
>>> --
>>>    ***Eric Payne***
>>>    1-619-786-4687
>>> erdapa1@gmail.com
>>>    www.lifeluvr.org
>>>
>>
>>
>>
>> --
>>    ***Eric Payne***
>>    1-619-786-4687
>> erdapa1@gmail.com
>>    www.lifeluvr.org
>>
>
>
>
> --
>    ***Eric Payne***
>    1-619-786-4687
> erdapa1@gmail.com
>    www.lifeluvr.org
>


-- 
   ***Eric Payne***
   1-619-786-4687
erdapa1@gmail.com
   www.lifeluvr.org

**Comment by lifeluvr** [comment]
I can make it ask for rights if that's better for alda...
I just want to get it going asap... it's a prototype.
It also tells you where it made the tmp folder when you run it.
I can hide that line and replace it with a custom welcome message if ya'll want!
Have you ran the app yet?


On 4/17/16, Eric Payne <erdapa1@gmail.com> wrote:
> Oh and you don't need any admin rights to run it either ;)
>
>
> On 4/17/16, Eric Payne <erdapa1@gmail.com> wrote:
>> (HINT: the email above is easily forwarded. If you do that once you'll
>> have
>> a copy in your 'Sent' email that you can get to whenever you want!)
>>
>> On Sun, Apr 17, 2016 at 3:54 PM, Eric Payne <erdapa1@gmail.com> wrote:
>>
>>> Ok, here it is!
>>> The 'Touch n' Go' Alda Terminal!
>>> Nothing to install!
>>> Run it and a terminal opens up with 'alda repl' already running for you!
>>> https://drive.google.com/open?id=0B3sPmoNzzT_od0dpRzJ2V1JKdHM
>>>
>>> On Sun, Apr 17, 2016 at 3:29 PM, Eric Payne <erdapa1@gmail.com> wrote:
>>>
>>>> About the download: There's 2 apps.One for connected and one for
>>>> wireless
>>>> ADB.
>>>>
>>>> On Sun, Apr 17, 2016 at 3:26 PM, Eric Payne <erdapa1@gmail.com> wrote:
>>>>
>>>>> Hi gang sorry I've been AWOL...
>>>>> Anyhow, I just got done compiling ADB into a windows app.
>>>>> For those who don't know... ADB is a set of binaries that enhance your
>>>>> command line options to communicate with your Android device in
>>>>> debugging
>>>>> mode.
>>>>> The binaries have to be installed at the root of c:\ too.. just like
>>>>> Alda!
>>>>> The app I made is really simple...
>>>>> It makes a temp file, unpacks the binaries and opens a terminal in
>>>>> that
>>>>> location.
>>>>> I can have it delete the temp file or keep it when closed, make a
>>>>> custom
>>>>> Alda icon and open a terminal with Alda powers!
>>>>> No installing... touch it and go!
>>>>> Delete it and it's gone!.. (unless we choose to save the temp file)
>>>>> I can even have it run a preliminary command for Alda when the
>>>>> terminal
>>>>> opens!
>>>>> I'll work on an example right now.
>>>>> Here's a link for the ADB terminals that don't need ADB installed ;)
>>>>> WARNING! 'one-touch' download!
>>>>> http://j.mp/ADB-CMD
>>>>>
>>>>> On Thu, Apr 14, 2016 at 11:36 AM, Dave Yarwood
>>>>> <notifications@github.com
>>>>> > wrote:
>>>>>
>>>>>> Closed #217 <https://github.com/alda-lang/alda/issues/217> via #218
>>>>>> <https://github.com/alda-lang/alda/pull/218>.
>>>>>>
>>>>>> —
>>>>>> You are receiving this because you are subscribed to this thread.
>>>>>> Reply to this email directly or view it on GitHub
>>>>>> <https://github.com/alda-lang/alda/issues/217#event-627812176>
>>>>>>
>>>>>
>>>>>
>>>>>
>>>>> --
>>>>>    ***Eric Payne***
>>>>>    1-619-786-4687
>>>>> erdapa1@gmail.com
>>>>>    www.lifeluvr.org
>>>>>
>>>>
>>>>
>>>>
>>>> --
>>>>    ***Eric Payne***
>>>>    1-619-786-4687
>>>> erdapa1@gmail.com
>>>>    www.lifeluvr.org
>>>>
>>>
>>>
>>>
>>> --
>>>    ***Eric Payne***
>>>    1-619-786-4687
>>> erdapa1@gmail.com
>>>    www.lifeluvr.org
>>>
>>
>>
>>
>> --
>>    ***Eric Payne***
>>    1-619-786-4687
>> erdapa1@gmail.com
>>    www.lifeluvr.org
>>
>
>
> --
>    ***Eric Payne***
>    1-619-786-4687
> erdapa1@gmail.com
>    www.lifeluvr.org
>


-- 
   ***Eric Payne***
   1-619-786-4687
erdapa1@gmail.com
   www.lifeluvr.org

**Comment by Pomax** [comment]
I have not, but also mostly because your solution is not related to this issue, but is a completely new one. Can you just open a new issue for it, migrate the details you posted here to the new issue, tag the people you think need tagging, and then delete the comments here? This issue got closed 3 days ago.

**Comment by lifeluvr** [comment]
I'll think about it...it seems like it's been a waste of time so far...

On 4/17/16, Mike Kamermans <notifications@github.com> wrote:
> I have not, but also mostly because your solution is not related to this
> issue, but is a completely new one. Can you just open a new issue for it,
> migrate the details you posted here to the new issue, tag the people you
> think need tagging, and then delete the comments here? This issue got closed
> 3 days ago.
>
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/alda-lang/alda/issues/217#issuecomment-211152949


-- 
   ***Eric Payne***
   1-619-786-4687
erdapa1@gmail.com
   www.lifeluvr.org

**Comment by Pomax** [comment]
I'm very precise when it comes to process. This is not my repo, so my attitude is no matter how awesome something is, if you talk about it in the wrong issue, especially one that's close, I'll mostly ignore it. File a new issue (or better yet, a PR) with your solution, and I'm sure people will find it and give it a shot (people won't find your questions and comments in a closed issue, so that's probably also part of why it feels like it's been a waste of time - only you and I, and dave, have seen your comments here)
