### ISSUE TITLE
Upgrade Alda to Java 8

### ISSUE THREAD

**Issue by bradarv90** [alda-lang/alda#219]
When running `boot -o /tmp`, the output is 

`clojure.lang.ExceptionInfo: java.lang.AssertionError: Assert failed: Alda requires JDK7 in order to build its uberjar, in order to provide out-of-the-box support for users who may have older versions of Java. Please install JDK7 and set the environment variable JDK7_BOOTCLASSPATH to the path to your JDK7 classpath jar, e.g. (OS X example) /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre/lib/rt.jar
                                         (not (empty? (System/getenv "JDK7_BOOTCLASSPATH")))
    data: {:file
           "/var/folders/3x/hm4t7k5x6cx8ndjnrxhy2vd40000gn/T/boot.user7574458188445515325.clj",
           :line 31}
java.util.concurrent.ExecutionException: java.lang.AssertionError: Assert failed: Alda requires JDK7 in order to build its uberjar, in order to provide out-of-the-box support for users who may have older versions of Java. Please install JDK7 and set the environment variable JDK7_BOOTCLASSPATH to the path to your JDK7 classpath jar, e.g. (OS X example) /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre/lib/rt.jar
                                         (not (empty? (System/getenv "JDK7_BOOTCLASSPATH")))
               java.lang.AssertionError: Assert failed: Alda requires JDK7 in order to build its uberjar, in order to provide out-of-the-box support for users who may have older versions of Java. Please install JDK7 and set the environment variable JDK7_BOOTCLASSPATH to the path to your JDK7 classpath jar, e.g. (OS X example) /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre/lib/rt.jar
                                         (not (empty? (System/getenv "JDK7_BOOTCLASSPATH")))`

According to [Oracle](https://java.com/en/download/faq/java_7.xml), java 7 is no longer available for download. Is there a workaround to this issue? Without a workaround, this will be severely limiting the amount of people who can contribute to Alda.

**Comment by jgkamat** [comment]
I've been able to compile alda with openjdk-8. Can you try setting `JDK7_BOOTCLASSPATH` to your java 8 classpath location?

**Comment by daveyarwood** [comment]
You can comment out the JDK7 requirement in the build.boot as a
workaround... I'll take a closer look when I have a minute.

The reason that's there is so that we can't release a version of Alda that
requires Java 8+. A lot of people (especially non-developers) have Java 7
installed.

**Comment by jgkamat** [comment]
I think there should be a way of setting the language level in the build settings. I'm not sure about boot, but in gradle there is an option that you can set like this: `sourceCompatibility = 1.7`

**Comment by daveyarwood** [comment]
JDK 7 is available for download here: http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html

It seems like it might be useful if we separated out the dev tasks of building Alda (for a release) and testing local changes to the client. Would it be easier if we had a `boot` dev task that ran the Java client locally with the provided args, without having to rebuild it? e.g. to test running the play command with the client with your local changes, you could run something like `boot client --args "play --file some_score.alda"`?

**Comment by daveyarwood** [comment]
I just added some functionality to the `boot dev` task, making it easier to test changes to the Alda client, REPL, and server, without having to build the project like before.

While I was at it, I rewrote / improved parts of the [development guide](https://github.com/alda-lang/alda/blob/master/doc/development-guide.md) -- any feedback/questions welcome!

@bradarv90 Does this help?

**Comment by bradarv90** [comment]
Yes. I can now build the project. Thank you all for helping me out!
