### ISSUE TITLE
repeatables? (:||, codas or even named macros?)

### ISSUE THREAD

**Issue by Pomax** [alda-lang/alda#223]
How does one set up a repeatable set of measures? I can't seem to find this in the blog post/README

**Comment by daveyarwood** [comment]
```
# repeat a note (note that whitespace is optional)
c * 2
d*2
e16 * 4
f16*8
g8 *3

# repeat multiple notes / events
[ c16 d e f g > c < ]*4
```

See [repeats](https://github.com/alda-lang/alda/blob/master/doc/repeats.md) in the docs for more info.

In the near future, we will have variables ( #131 ) to streamline this even further. They'll work like this:

```
# define a named event sequence
mySequence = [ c16 d e f g > c < ]

# play it 4 times
mySequence * 4
```

**Comment by Pomax** [comment]
cool, thanks!
