### ISSUE TITLE
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

### ISSUE THREAD

**Issue by Pomax** [alda-lang/alda#224]
Ran into this interesting problem on Windows 8.1, with a fix mentioned in http://stackoverflow.com/questions/16428098/groovy-shell-warning-could-not-open-create-prefs-root-node working just fine (there was no `prefs` key in the `javasoft` registry setting. Adding one fixed this), but might be worth appending the README.md with for Windows users.

**Comment by daveyarwood** [comment]
Wow, that's some crazy Windows voodoo I completely don't understand, lol!

Sure, I'd love a Pull Request making this available for Windows users. I think maybe the best thing would be to create a `doc/troubleshooting.md` with a section for Windows-specific issues. Then we could link to that in the README. I'd rather keep scary error messages out of the README :)

**Comment by Pomax** [comment]
always a good idea, I'll see about sending a PR up later today

**Comment by daveyarwood** [comment]
Thanks!

**Comment by daveyarwood** [comment]
Closing this for now -- would still happily accept a PR though :)

**Comment by Pomax** [comment]
usually better to keep it open until a few weeks later - I got massively sidetracked over the weekend, and having an issue so that the PR can say "fixes #..." is always better than a rogue PR =)

**Comment by daveyarwood** [comment]
Fair enough - re-opening! :)

**Comment by Pomax** [comment]
PR filed.
