### ISSUE TITLE
Potential bug with protecting/unprotecting MIDI notes

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda#231]
In 1.0.0-rc17 I implemented a little system in alda.sound.midi where a note is protected from being stopped by another note with the same MIDI number if they overlap at all. I didn't factor in the MIDI channel number at all, though, so that's probably a bug. I don't have time to investigate at the moment, so leaving this issue here as a placeholder.

**Comment by daveyarwood** [comment]
Bug confirmed. Fix on the way.

**Comment by elyisgreat** [comment]
great. will test once the fix has been released.

**Comment by daveyarwood** [comment]
A little context, for posterity: the bug is that if multiple instruments played the same note at the same time, the note will only be stopped once, leaving the other one ringing out forever.

The fix is for each instrument to ignore what notes are being played by other instruments -- it doesn't matter, because those instruments are using separate MIDI channels.

**Comment by daveyarwood** [comment]
Fixed in [1.0.0-rc18](https://github.com/alda-lang/alda/releases/tag/1.0.0-rc18).
