### ISSUE TITLE
Reference pitch and transposition attributes

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#236]
The way I found out #235 was by trying to change the key of my score. As there is no official way of doing this, I performed my "hack" of adding `+` characters, however this led to the code being too long. It's also quite inefficient. So what I suggest as a simple implementation is having a `tuning-constant` attribute, which would define the frequency for A4. So, for example, the default would be `(tuning-constant 440)`, and setting it to `(tuning-constant 261.6)`, for example, would make A4 sound like a C4. 

Now, transposition operators have already been discussed in #129, but their use is mainly an operator on notes and event sequences. And even if they were a settable attribute, you might run into problems with a line like `(transpose 3) g g^2`, where it's not clear what applies to what. Having a separate tuning constant attribute would solve this and also be simple to implement.

**Comment by daveyarwood** [comment]
I like the idea of using this concept in order to set a "reference pitch," e.g. `(reference-pitch 430)` if you want to write music that sounds like it's being played on period instruments of the classical period, when it was common to tune A4 to 430 Hz instead of 440.

I'm not sure I agree with using this as a substitute for the proposed `transpose` attribute, though. I think if that attribute is used in combination with the `^` operator, it would have a combining effect, i.e. `(transpose 3) c^2` would transpose the C up 5 (half-?)steps.

**Comment by elyisgreat** [comment]
Yeah. I'm not suggesting that the `tuning-constant` would be a replacement for the transpose operator. It's more a way to pitch shift across an entire instrument as opposed to over event sequences. 

The problems with the `transpose` attribute that I was detailing was the attribute-operation duality, which I think I will detail in #129.

**Comment by daveyarwood** [comment]
I'm envisioning being able to use `transpose` at the beginning of an instrument part, effectively pitch-shifting the entire instrument. This could be handy for writing music for [transposing instruments](https://en.wikipedia.org/wiki/Transposing_instrument), e.g. to write music for a Bb clarinet playing in the key of Bb, you could do `clarinet: (transpose -2)` and write the part in C major, and it'll sound 2 half-steps lower.

I could see both `transpose` and `reference-pitch` (or `tuning-constant`, whatever we end up calling it) being useful together, too. Like, maybe someone will want to write a piece for transposing instruments and tune them all to A430.

**Comment by elyisgreat** [comment]
Yeah. That would mean that the problem described in #129 would be solved by completely separating the transposition *operator* and the transposition *attribute*.

**Comment by daveyarwood** [comment]
Ok, yeah, I think we're on the same page. Perfect!

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-core/issues/21.
