### ISSUE TITLE
variable issues

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#253]
Lots of issues with variables in the latest release.

* When declaring variables, there's a bizarre bug that happens. 

If the variable happens to contain anything that is repeated an odd number of times, it will throw an error. However if it is encased in an event block, no error is thrown.

```
foo = [c c]*3
#throws an error
foo = [[c c]*3]
#no error
```

* If the variable happens to contain anything that is repeated an even number of times, it will throw an error, but only on evaluation. However if it is encased in an event block, no error is thrown.

```
foo = [c c]*2
foo
#throws an error
foo = [[c c]*2]
foo
#no error
```

* Variables containing empty clojure expressions will throw an error upon evaluation, even though when the equivalent code is run, no error is thrown (it's just treated as nothing).

```
foo = () c d e f
foo
#throws an error
```

There are probably more, but these are the ones I've found so far...

**Comment by elyisgreat** [comment]
Found another one. If a variable used itself (already defined) in its definition more than once in a score, an error is thrown. This, however, was fixed in rc27 (so I guess it's not all breakages).

```
notes = c d e
notes = notes f g
notes = notes a b
notes
#throws an error in rc24-rc26
```

**Comment by daveyarwood** [comment]
Well that was interesting!

Both bugs are fixed in [1.0.0-rc28](https://github.com/alda-lang/alda/releases/tag/1.0.0-rc28).

Thanks a lot for finding and reporting all these bugs, it's a big help!

**Comment by elyisgreat** [comment]
those were the only ones I found, however there may have been more. What was causing these bugs?

**Comment by daveyarwood** [comment]
They were just edge cases related to using a) repeated event sequences and b) empty Clojure expressions within a variable definition, both things I hadn't tried before.
