### ISSUE TITLE
Event handlers for MIDI input

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda#254]
I was daydreaming today and it occurred to me that we could add a live performance aspect to Alda by allowing users to define event handlers for MIDI events from input (e.g. a USB MIDI controller), using inline Clojure code.

Pseudocode representing the kind of thing a score writer could potentially do in an Alda score:

```
(on-midi-note [{:keys [midi-note velocity]}]
  (part "double-bass"
    (volume velocity)
    (note (pitch midi-note)
          (duration (note-length 1)))))
```

Each time a MIDI note-on message is received, the body of the user-defined function would be executed.

**Comment by elyisgreat** [comment]
Nice. I'm also hoping that export to MIDI (or other types of audio files, because I really like the "Alda soundfont") is added soon. Being able to send alda scores to others without requiring them to have Alda installed would be quite nice.

**Comment by daveyarwood** [comment]
@elyisgreat Yeah, I'd definitely like to do that too -- tracking those features in #62 and #145 .

**Comment by daveyarwood** [comment]
Related: #259 (that issue is MIDI OUT, this one is MIDI IN)

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-sound-engine-clj/issues/6.
