### ISSUE TITLE
Beginner-friendly issue label

### ISSUE THREAD

**Issue by MunGell** [alda-lang/alda#291]
Hi guys,

I am a maintainer of [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners) repository.
I recently got a PR to add Alda to the list: https://github.com/MunGell/awesome-for-beginners/pull/47

I am not sure if `low-haging fruit` is the right label for the beginners since you also have `up-fo-grabs` label. I appreciate if you can clarify which label is more suitable for people who just started programming or looking for opportunity for their first open source contribution.
If non of this labels is matching this criteria - please let me know.

Thanks

**Comment by daveyarwood** [comment]
Hi!

Sorry for the confusion -- `low-hanging-fruit` is the label we use for beginner-friendly issues.

`up-for-grabs` just means an issue has been triaged and ready to be started on -- the issue may or may not be beginner-friendly.

**Comment by MunGell** [comment]
Cool, thanks!
