### ISSUE TITLE
Exporting images

### ISSUE THREAD

**Issue by MinaBombo** [alda-lang/alda#297]
Is there a feature of exporting the script to an image of the musical note?

**Comment by daveyarwood** [comment]
Not yet.  I think it would be most useful to export a .pdf of the score, which could then be converted to any image format you'd like.

Ideally the first step toward that would be to export MusicXML: https://github.com/alda-lang/alda-core/issues/3

The MusicXML could be converted into high-quality sheet music by translating it into a [LilyPond](http://lilypond.org) score.

LilyPond can easily be exported to .pdf.

If possible, I would like to automate this whole process and provide different export modes from Alda, so you could run a command something like `alda export --lilypond` or `alda export --pdf`. Obviously, there is some work to do before we can get there, although it is high on my list of priorities.
