### ISSUE TITLE
Turn off logging by default

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda#30]
Timbre logs a bunch of stuff at the DEBUG level, which is all visible out of the box when you clone this repo and start to play around with Alda. I put a little blurb in the README about how to turn this off, but it would be nice if it were off by default. I'm sure there is a way to do this with Timbre, just need to look for it.

**Comment by crisptrutski** [comment]
Boot-style options of `-v`, `-vv` or `-vvv` for escalating levels of logging could be a nice interface for cranking things back up

**Comment by daveyarwood** [comment]
Brilliant! I might hack that in today. :saxophone: :notes:
