### ISSUE TITLE
There's only a Windows executable and an Amiga disk image...

### ISSUE THREAD

**Issue by Stokestack** [alda-lang/alda#310]
...where the downloads are listed.

I'm on Mac OS. Guess I'll try the source...

**Comment by daveyarwood** [comment]
Hi @Stokestack ,

Each release includes 2 executables: one for Windows (`alda.exe`) and one for Unix/Linux, including MacOS (`alda`).

For more information on installing Alda on MacOS: https://github.com/alda-lang/alda#mac-os-x--linux
