### ISSUE TITLE
There's no Mac executable among the releases. 

### ISSUE THREAD

**Issue by Stokestack** [alda-lang/alda#311]
The instructions say to download the Mac executable here: https://github.com/alda-lang/alda/releases/tag/1.3.2

There isn't one there; not that I can find. That is the entire substance of this issue: There is no Mac executable available for download on this page. [Here is a screen shot.](https://imgur.com/a/TEScEkS)

**Comment by daveyarwood** [comment]
I'm sorry for the confusion. `alda` is the MacOS executable. It is not an Amiga disk image. Maybe your browser is set up to download it with a `.dms` extension by default? There should be no file extension, it's just `alda`.

**Comment by Stokestack** [comment]
Thanks. Turns out that this is a known Safari defect that has been going on for **[years](https://forums.macrumors.com/threads/safari-erroneously-adding-dms-extension-to-downloads.2080108/)**.

Sad.
