### ISSUE TITLE
Add vscode plugin link to the readme

### ISSUE THREAD

**Issue by JesseChua94** [alda-lang/alda#312]
I was thinking of writing a vscode plugin for a syntax highlighter when i discovered it deep in the slack channels. It would be great to add this link to the readme!

https://marketplace.visualstudio.com/items?itemName=abhi18av.alda-vscode

**Comment by daveyarwood** [comment]
Oh, cool. I didn't realize this existed! I'll add it to the README.

**Comment by daveyarwood** [comment]
Closed via https://github.com/alda-lang/alda/commit/7ba86ed7e80069c89fe3338a5ccb1933fca6c3a7
