### ISSUE TITLE
ERROR null when using (set-duration (ms 2000))

### ISSUE THREAD

**Issue by dhpiggott** [alda-lang/alda#318]
Given the documentation at https://github.com/alda-lang/alda/blob/07143d6fd85559171554e65023d37cf63402e9e7/doc/attributes.md#duration I would expect this to play the note that follows for 2 seconds:

```
piano:
  (set-duration (ms 2000)) c
```

But I get this error:

```
➜  ~ ./alda play --file apollo-test.alda
[27713] Parsing/evaluating...
[27713] ERROR null
```

This is the Alda version:
```
➜  ~ ./alda version
Client version: 1.4.3
Server version: [27713] 1.4.3
```

**Comment by daveyarwood** [comment]
I've confirmed that this is no longer an issue in Alda 2, although the syntax has changed a bit. Because the new (non-Clojure) embedded Lisp is strongly typed, I opted to add a separate `set-duration-ms` function that sets the duration in milliseconds instead of beats. The following works:

```alda
piano: (set-duration-ms 2000) c d e
```
