### ISSUE TITLE
moar docs

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda#32]
So far we just have information about Alda the language (how the syntax works, etc.) in the wiki. 

To add:
- alda.lisp
- alda.repl
- alda.now
- a landing page with links to the above topics

**EDIT 9/24:** Also, we should move everything definitive in the wiki to markdown files in a `doc/` folder in the root of the project. (Planning documents can stay in the wiki)

**Comment by daveyarwood** [comment]
alda.now usage should also be documented in the README, at least with a link to the documentation in the wiki

**Comment by daveyarwood** [comment]
I've started adding some of the lower-level info to a Developer Guide in CONTRIBUTING.md. Most Alda users (i.e. end users) probably won't get much use out of this, but it at least serves as good documentation for alda.lisp and alda.now, which you would only be using if you're a Clojure programmer anyway.

Open question: Should some of this info be moved to the wiki?

**Comment by crisptrutski** [comment]
Personally I'm a fan of "docs in the repo, not the wiki" - this is especially true once it comes to guides and technical information - how do you collaborate on the "version 2" documentation before version 2 hits `master` without confusing users? How do users find documentation for old version?

[Here's a piece by someone with similar opinions and who spent more time explaining himself](http://www.yesodweb.com/blog/2015/08/thoughts-on-documentation)

**Comment by daveyarwood** [comment]
OK, after reading that blog post, I'm sold! We should include all our docs in the repo itself, and link to a "landing page" in the README.

**Comment by kirbyfan64** [comment]
Have you guys ever considered using ReadTheDocs? I use it for several of my projects, and it works insanely well.

**Comment by daveyarwood** [comment]
@kirbyfan64 ReadTheDocs looks pretty cool -- looks like it syncs with git repos. Might be a good place to host our documentation once it's starting to come together a little more.

**Comment by daveyarwood** [comment]
I've officially gotten started by [moving all the docs from the wiki to a `doc/` folder](https://github.com/alda-lang/alda/blob/master/doc/index.md). It has a dumb landing page and everything!

At this point, we can start taking PRs to edit the docs. I will work on documenting all the stuff I said on that first post -- will close this issue once those things are documented.

**Comment by daveyarwood** [comment]
Also, TODO: Make the README more concise by moving specific info into the docs.

For example, we can move most of the Installation section into a "Getting Started" or "Installation" page in the docs.
