### ISSUE TITLE
"this will take a few minutes" message when downloading FluidR3

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda#34]
It takes at least a few minutes to download the 125 MB FluidR3 soundfont (packaged as an optional Maven dependency). We already warn users in the README that this will take a while the first time they run Alda, but it would be better if we also print something out to the console like "Downloading FluidR3 MIDI soundfont. This will take a few minutes." Otherwise, users might wonder if the Maven download is stalling (when in fact, it just takes longer than the majority of Maven dependencies)

**Comment by okal** [comment]
A progress indicator would be even better, assuming that that information is exposed by the HTTP client.

**Comment by daveyarwood** [comment]
@okal that would be ideal, but it would have to be a change upstream in [boot-clj](https://github.com/boot-clj/boot)

I happen to work with the creators of Boot -- I can at least mention that idea :)

**Comment by daveyarwood** [comment]
Once we reach version 1.0.0, installing FluidR3 will be a separate process (but aided by the Alda CLI client) and will no longer be packaged or used as a dependency, neatly solving this issue. Keeping this issue open until that happens.

**Comment by okal** [comment]
Great. Nice work, Dave.
