### ISSUE TITLE
Alda CLI does not always recognize AdoptOpenJDK installation

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#346]
Moved from alda-lang/alda-core#74. 

> Not sure if this belongs here or in alda-client-java. I recently replaced my Java installation with an AdoptOpenJDK installation.
> ```
> PS C:\Users\elyis> java -version
> openjdk version "11.0.4" 2019-07-16
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
> OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
> ```
> However, `alda` simply does not detect it:
> ```
> PS C:\Users\elyis> alda
> This application requires a Java Runtime Environment 1.7.0
> ```
> Any idea what's going on?

I have since found out that the alda CLI *does* recognize AdoptOpenJDK 8, but only if the option to add the required registry keys is enabled in the AdoptOpenJDK installer. AdoptOpenJDK 11 installations do not seem to be recognized at all.

**Comment by daveyarwood** [comment]
I'm closing this issue for now, as there hasn't been any further discussion in the last year, but I am curious if it's still an issue with Alda 2. If anyone is still seeing issues with the latest release of Alda, let me know and we can re-open this!
