### ISSUE TITLE
building-the-alda-executable.md boot-clj link is invalid

### ISSUE THREAD

**Issue by yonderbread** [alda-lang/alda#357]
# 🐞 Bug report 🐞

## Description
The ![link to boot-clj](https://github.com/alda-lang/alda/blob/master/doc/building-the-alda-executable.md#L11) is now a ![store for shoewear](https://boot-clj.com/).

## Steps to Reproduce
1. click link
2. buy some Keen boots

## Expected Behavior
Links should direct to this ![Github repo](https://github.com/boot-clj/boot).

**Comment by daveyarwood** [comment]
That is hilarious! :laughing: 

I'll update it to the GitHub pages site for Boot: https://boot-clj.github.io/

**Comment by daveyarwood** [comment]
Fixed. Thanks for reporting this!

**Comment by yonderbread** [comment]
Haha ya I found it pretty funny, and of course! Take care :)
