### ISSUE TITLE
(comment "content") seems to be no longer supported in Alda 2

### ISSUE THREAD

**Issue by firmart** [alda-lang/alda#366]
I noticed the new release of Alda 2 through Dave's blogpost and upgraded Alda from v1.4.2 to v2.0.0. I tried to play old scores I grabbed from Internet last year, but it seems that the syntax `(comment "content")` is no longer supported in Alda 2.

To reproduce
-------------------

1. Create a `test.alda`
```lisp
(comment "content")
``` 
2. Run `alda play -f test.alda`. It will error out:
```bash
test.alda:1:2 Unresolvable symbol: comment
```

Alda doctor
----------------
```
 alda doctor
OK  Parse source code
OK  Generate score model
OK  Find an open port
OK  Send and receive OSC messages
OK  Locate alda-player executable on PATH
OK  Check alda-player version
OK  Spawn a player process
OK  Ping player process
OK  Play score
OK  Export score as MIDI
OK  Locate player logs
OK  Player logs show the ping was received
OK  Shut down player process
OK  Spawn a player on an unknown port
OK  Discover the player
OK  Ping the player
OK  Shut the player down
OK  Start a REPL server
nREPL server started on port 43357 on host localhost - nrepl://localhost:43357
OK  Interact with the REPL server
```

Environment
------------------
 Ubuntu 20.04.2 with Alda 2.0.0

Notes
--------
- I've read the Change logs and the migration guide, didn't find something related. Maybe this change occurred prior Alda 2. 
- Apologies to not use the full bug report template, I think this is rather a documentation issue: what is the comment syntax ?

Thanks for all the good work.

**Comment by daveyarwood** [comment]
Thanks for the kind words!

`(comment ...)` is indeed no longer available in Alda 2. It was only available in Alda 1 "by accident," because it was provided by the Clojure runtime. At one point, I was recommending that folks who wanted a long comment syntax could use `(comment ...)` instead, but that was never something that I intended to support long term. In Alda 2, if you want to comment out many lines, the only way to do it is to prepend each line with `#`.

**Comment by daveyarwood** [comment]
> I think this is rather a documentation issue: what is the comment syntax ?

Excellent point! Let's keep this issue open until there is easy-to-find documentation about the comment syntax. I think it would make sense to add a short `doc/comments.md` to the docs folder.

**Comment by daveyarwood** [comment]
I've added documentation about comments here: https://github.com/alda-lang/alda/blob/master/doc/comments.md
