### ISSUE TITLE
alda broke my computer

### ISSUE THREAD

**Issue by fiatjaf** [alda-lang/alda#38]
first I saw this:

```
fiatjaf@mises ~ $ alda repl

boot: script file not found: build.boot
Perhaps /usr/local/bin/alda should have the .boot extension?

Usage: boot :strap
       boot [arg ...]
       boot <scriptfile.boot> [arg ...]

Create a minimal boot script: `boot :strap > build.boot`

fiatjaf@mises ~ $ 
fiatjaf@mises ~ $ alda --help
^Cfiatjaf@mises ~ $ alda boot :strap > build.boot
boot: no boot.core dependency specified in build.boot

Usage: boot :strap
       boot [arg ...]
       boot <scriptfile.boot> [arg ...]

Create a minimal boot script: `boot :strap > build.boot`
```

then I ran `boot :strap > build.boot` and `alda repl` again.

the screen went black.

**Comment by daveyarwood** [comment]
... yikes! :grimacing:

The messages you're seeing appear to be from Boot 1.x.x, which did not support running standalone scripts like the `alda` start script. Installing [the latest version of Boot](https://github.com/boot-clj/boot#install) (2.x.x) and trying it again should do the trick.

**Comment by fiatjaf** [comment]
I installed the newest version of Boot and run `alda repl` again. It printed some things (like "downloading and installing this and that"), I went to the kitchen and when I came back the screen was not black, but frozen and not responding.

**Comment by daveyarwood** [comment]
This is expected behavior -- the first time you run Alda, it takes at least a few minutes to install a 125 MB soundfont which will make MIDI sound a lot nicer. You should just leave it running for a while, and it should be done within 5-10 minutes at the most. 

If you'd prefer, you can skip the download step and just use Java's built-in MIDI sounds, although they don't sound as realistic. To do this, run `alda repl --stock`.

**Comment by fiatjaf** [comment]
Is it expected behavior to totally freeze the computer? I think the problem I have is probably low memory. My computer is very modest.

**Comment by daveyarwood** [comment]
Are you sure it is actually freezing your computer? It is normal for it to say something like "Retrieving FluidR3 from clojars.org" and there is no indication of the status of the download, or anything. It can take 5-10 minutes for FluidR3 to download, as it is a fairly large file (125 MB).
