### ISSUE TITLE
[homebrew] alda 2.0.2 test failure

### ISSUE THREAD

**Issue by chenrui333** [alda-lang/alda#385]
👋  trying to upgrade the homebrew formula to the latest release build, but runs into the regression test failure

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1278349]

goroutine 8 [running]:
alda.io/client/system.CleanUpStaleStateFiles.func1(0xc00002c510, 0x2e, 0x0, 0x0, 0x15de540, 0xc0002007b0, 0x2e, 0xc00002c510)
	alda.io/client/system/player_management.go:38 +0x29
path/filepath.WalkDir(0xc00002c510, 0x2e, 0x156a6e8, 0xc00002c510, 0x2e)
	path/filepath/path.go:463 +0x8b
alda.io/client/system.CleanUpStaleStateFiles(0x0, 0xc000241d10)
	alda.io/client/system/player_management.go:35 +0x151
alda.io/client/system.ReadPlayerStates(0xc000296080, 0x1a, 0x1, 0x0, 0x0)
	alda.io/client/system/player_management.go:100 +0x37
alda.io/client/system.FillPlayerPool(0x0, 0x0)
	alda.io/client/system/player_management.go:332 +0xc5
alda.io/client/cmd.fillPlayerPool.func1()
	alda.io/client/cmd/root.go:79 +0x26
alda.io/client/cmd.startBackgroundActivity.func1(0x156a388, 0xc00008e300)
	alda.io/client/cmd/root.go:44 +0x27
created by alda.io/client/cmd.startBackgroundActivity
	alda.io/client/cmd/root.go:43 +0xcc
```

relates to Homebrew/homebrew-core#82363

**Comment by daveyarwood** [comment]
I'm not very familiar with how Homebrew packages work. Is there a way that I can repro the problem locally?

**Comment by daveyarwood** [comment]
Also: I really appreciate your effort to make Alda available in Homebrew, that's super awesome! :100:

**Comment by daveyarwood** [comment]
@chenrui333 I happened to find a bug that I think may have been causing this problem with the Homebrew test.

It's fixed in Alda 2.0.3, which I've just released. Would you mind giving the new version a try and see if resolves the problem?

**Comment by chenrui333** [comment]
Yes, I am gonna try a new release bump now. :)

**Comment by chenrui333** [comment]
New release bump, Homebrew/homebrew-core#82832

**Comment by daveyarwood** [comment]
I think this issue is resolved, so I'm closing it. But do let me know if you continue to have any problems with the Homebrew build!

**Comment by chenrui333** [comment]
Yes, the issue is resolved. Thanks for the fix!! 🎉
