### ISSUE TITLE
Can't switch octave within a chord in cram expression

### ISSUE THREAD

**Issue by wiwikuan** [alda-lang/alda#388]
# 🐞 Bug report 🐞

## Description

Switching octave using `>` **within a chord** inside cram expression results in weird behavior.

## Steps to Reproduce
`piano: o4 c4./g/>c` sounds normal.
`piano: o4 c4./g/>c o4 c4/g/>c` sounds normal.
But if I say `piano: {o4 c4./g/>c o4 c4/g/>c}4` it plays only one long "C" note.
But if I don't switch octave, `piano: {o4 c4./g/b o4 c4/g/b}4` plays fine.
If the octave switch is not within a chord, like `piano: {o4 c4 d >c}4`, it plays normal though.

## Environment
macOS 10.14

**Alda version:**

```
$ alda version
alda 2.0.3
```

**Comment by daveyarwood** [comment]
Thanks for the report! I'll dig into this when I can and work on a fix.

**Comment by daveyarwood** [comment]
I've fixed this in Alda 2.0.5, which is available now. Thanks again for reporting this bug!
