### ISSUE TITLE
Worked for a while then stopped producing sound on Linux

### ISSUE THREAD

**Issue by anderspitman** [alda-lang/alda#39]
Linux Mint 17. I can provide logs if you tell me what you need. Hoping someone knows off the top of their head what the issue might be. I don't have time to debug it at the moment.

**Comment by daveyarwood** [comment]
Hmm... that's strange. Is this in the Alda REPL, or playing a score from the command line via `alda play`?

**Comment by MerreM** [comment]
Neither works for me :(

**Comment by anderspitman** [comment]
REPL

**Comment by daveyarwood** [comment]
Did sound stop working altogether in the REPL?

i.e. if you start a new REPL session now by running `alda repl`, and type in `piano: c d e`, do you hear anything? Do you see any debug logs?

**Comment by anderspitman** [comment]
Sorry, I was using incorrect syntax.
