### ISSUE TITLE
Can not play in Sublime text

### ISSUE THREAD

**Issue by mx91064728** [alda-lang/alda#397]
# 🐞 Bug report 🐞

## Description

I use Sublime Text as the editor, the error comes out when I build the code with ctrl + B:

{
Oops! Something went wrong:
  open "C:\ALDA\test.alda": The filename, directory name, or volume label syntax is incorrect.

This might be a bug. For help, consider filing an issue at:
  https://github.com/alda-lang/alda/issues/new/choose

Or come chat with us on Slack:
  https://slack.alda.io
}

However, I can run it in cmd window with alda play -f C:\ALDA\test.alda
I already installed the ALDA package in Sublime Text, the code has color in different syntax.

## Steps to Reproduce

1.
2.
3.
4.

## Actual Behavior

![擷取](https://user-images.githubusercontent.com/54937712/132174910-976db7cb-58b5-4e63-a2d4-d43ded439e45.JPG)

## Environment

**Operating system and version:**

**Alda version:**

```
$ alda version
alda 2.0.5
```

```
$ alda-player info
alda-player 2.0.5
log path: C: \Users\ASUS\AppData\Local\alda\cache\logs
```

**Health check:**

```
$ alda doctor
[32mOK [0m Parse source code
[32mOK [0m Generate score model
[32mOK [0m Ensure that there are no stale player processes
[32mOK [0m Find an open port
[32mOK [0m Send and receive OSC messages
[32mOK [0m Locate alda-player executable on PATH
[32mOK [0m Check alda-player version
[32mOK [0m Spawn a player process
[32mOK [0m Ping player process
[32mOK [0m Play score
[32mOK [0m Export score as MIDI
[32mOK [0m Locate player logs
[32mOK [0m Player logs show the ping was received
[32mOK [0m Shut down player process
[32mOK [0m Spawn a player on an unknown port
[32mOK [0m Discover the player
[32mOK [0m Ping the player
[32mOK [0m Shut the player down
[32mOK [0m Start a REPL server
nREPL server started on port 54314 on host localhost - nrepl://localhost:54314
[32mOK [0m Find the REPL server
[32mOK [0m Interact with the REPL server
[32mOK [0m Shut down the REPL server
```

**Logs:**

```
    
```

**Comment by daveyarwood** [comment]
Hi @mx91064728 , thanks for reporting this!

Given that you said that this works in your terminal, I think this might be a bug in [the Alda plugin for Sublime Text](https://github.com/erinzm/sublime-alda).

@erinzm Do you have any ideas about what might be causing this?

**Comment by daveyarwood** [comment]
Closing this for now. Happy to reopen it if there is something we can do about this on the Alda side!
