### ISSUE TITLE
Can't play alda file in window

### ISSUE THREAD

**Issue by 715yeung** [alda-lang/alda#399]
# 🐞 Bug report 🐞

## Description

I tried to play alda file at window system , and that's not work ,even i use the file from the example

``` alda play -c "..."``` is work , can play some suff
```alda repl ``` is work too
and i use the jdk from eclipse foundation version are 16.0.2.7

```
PS C:\Users\...> alda play --file bach_cello_suite_no_1.alda
bach_cello_suite_no_1.alda:1:1 Unexpected '' at the top level
```

## Steps to Reproduce

1.
2.
3.
4.

## Environment

**Operating system and version:**

**Alda version:**

```
$ alda version
alda 2.0.5
```

```
$ alda-player info
alda-player 2.0.5
log path: C:\Users\..
```

**Health check:**

```
$ alda doctor
[32mOK [0m Parse source code
[32mOK [0m Generate score model
[32mOK [0m Ensure that there are no stale player processes
[32mOK [0m Find an open port
[32mOK [0m Send and receive OSC messages
[32mOK [0m Locate alda-player executable on PATH
[32mOK [0m Check alda-player version
[32mOK [0m Spawn a player process
[32mOK [0m Ping player process
[32mOK [0m Play score
[32mOK [0m Export score as MIDI
[32mOK [0m Locate player logs
[32mOK [0m Player logs show the ping was received
[32mOK [0m Shut down player process
[32mOK [0m Spawn a player on an unknown port
[32mOK [0m Discover the player
[32mOK [0m Ping the player
[32mOK [0m Shut the player down
[32mOK [0m Start a REPL server
nREPL server started on port 49661 on host localhost - nrepl://localhost:49661
[32mOK [0m Find the REPL server
[32mOK [0m Interact with the REPL server
[32mOK [0m Shut down the REPL server
```

**Logs:**

```
```

**Comment by daveyarwood** [comment]
Hi @715yeung , thanks for reporting this!

I think the immediate problem is that this error message isn't very good:

> Unexpected '' at the top level

There appears to be some kind of unexpected character at the beginning of the file you're attempting to play, however, the error message doesn't really say what character it is. I think it's some kind of character that doesn't have a visual representation.

I would have guessed that it's a [control character](https://en.wikipedia.org/wiki/Control_character) of some kind, but we do [check for control characters](https://github.com/alda-lang/alda/blob/57644127cfeee5f2ab2c506d62fbe9fe59a83664/client/parser/scanner.go#L48-L49) and print the code point, and that's not what's happening here. So, it must be some other kind of unexpected character. Maybe a Unicode character of some kind?

If you could attach the file you're trying to play to this issue, that would be helpful to me in debugging this issue.

**Comment by 715yeung** [comment]
Hi @daveyarwood 
Thanks for your advice,
I follow your suggestion and use the notepad++ change the encoding from uft-8 BOM to uft-8 , then its work
so i thought it should be the encoding problem 
Thanks very much for your help and hope the result can help
