### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by kirbyfan64** [alda-lang/alda#40]
One of the chord examples is:

```
o4 c1/e/g/>c4 < b a g | < g+1/b/>e
```

However, wouldn't this cause the lower C note to be a quarter note instead of a whole note?

**Comment by daveyarwood** [comment]
I think you may be imagining the chord upside-down. Here is the sheet music version of that code snippet:

![](http://daveyarwood.github.io/assets/2015-08-23-sheet-music-11.png)

The `c1/e/g/>c4` part is constructing the chord from the bottom-up. The first 3 notes are the C-E-G whole note triad, and the top note is a C quarter note in the next octave up. Does that make sense?

**Comment by kirbyfan64** [comment]
Ugh, I wasn't viewing it upside down, I for some weird reason though `c1` was a quarter note and `c4` was a whole note. :/ Sorry for the noise!

**Comment by daveyarwood** [comment]
No problem, happy to help :)
