### ISSUE TITLE
First run spews "accept incoming network notifications" all over my screen

### ISSUE THREAD

**Issue by sqqqrly** [alda-lang/alda#400]
# 🐞 Bug report 🐞

## Description
I installed on my Mac (Big Sur 11.4).  When I ran "aldi repl" about 9 windows popped up!  Clicking deny does not clear them.  This is very annoying.

Eventually the Mac clean up the mess of windows (after a few minutes).

## Steps to Reproduce

1. Install
2. run "aldi repl"

Killed aldi. Ran again.  Window pops again.

The windows have two flavors.  They have deny and allow buttons.  Deny does nothing. Window remains.  I will not click allow.
- Do you want the application “alda” to accept incoming network connections?
- Do you want the application “java” to accept incoming network connections?

## Environment

**Operating system and version:**

**Alda version:**

```
$ alda version
2.0.5 (installed via brew)
```

```
$ alda-player info

```

**Health check:**

```
$ alda doctor

```

**Logs:**

```
```

**Comment by daveyarwood** [comment]
This seems like a general issue with running applications on macOS.

Does [this information](https://discussions.apple.com/thread/7418556) help?

**Comment by sqqqrly** [comment]
No.  That link suggests "add <your app here> to the list of permitted apps".   Ummm no.

**Comment by sqqqrly** [comment]
Why is aldi asking for incoming network connections **at all**?

**Comment by daveyarwood** [comment]
When you run `alda repl`, it starts an Alda REPL server, which can be connected to from other `alda repl` client processes. Communication is done over TCP via the OSC protocol.

**Comment by sqqqrly** [comment]
Interesting.  Thanks for the reply.

**Comment by sqqqrly** [comment]
Please close this issue.
