### ISSUE TITLE
How to make Pedal On and Off in Alda

### ISSUE THREAD

**Issue by rolandng01** [alda-lang/alda#412]
I like to play piano. It will be nice if someone tells me how to add Pedal On and Off information to the code that Alda plays. Thanks.

**Comment by daveyarwood** [comment]
There isn't explicit support for Pedal On/Off in Alda yet (although it's something I'd like to implement, see #320).

In the meantime, you can get a similar effect by setting `quant` to a value > 100, meaning the notes should ring out for longer than the length of the note.

```alda
piano:
  (quant 250)
  [ o4 c8 e g > c e < g > c e ]*2
  [ o4 c8 d a > d f < a > d f ]*2
  [ o3 b8 > d g > d f < g > d f ]*2
  [ o4 c8 e g > c e < g > c e ]*2
```

This isn't exactly the same thing as using the sustain pedal, but it at least sounds close to the desired effect!

**Comment by rolandng01** [comment]
Thank you for your response. Suddenly I think of an idea. Usually the piano notes compose of three main parts (i) the main melody (ii) the chord and (iii) the base. Why piano would like to use the pedal is that the left hand usually can hardly control (ii) & (iii) at the same time. Usually the base starts at the beginning of a chord session and is hoped that it can last for the whole chord session. So, the piano is making use of the Pedal and the player can continue to play chord without worrying. 

That means usually for one chord session, Pedal is on, base is played at first, chord is then played, Pedal off and the chord session ends. So, I can just put the base in another voice and serves that effect. My example is as follows.

(volume! 100)
(key-signature! "e- a- b-")
(tempo! 62)
piano:
V1: o4
b8 >g2 f8 g f4. e4 <b8 
>g4 {c8 c+8 c8 c-8 c2}8 >c4 <g8 b4. a4 g8
f4. g4 d8 e4. c4.
<b8 >>d c <b16 a g a c d e4.
V2: o3
r4 g8/>e <b/>e/g r <a/>d c-/d/a r <g/>e <b/>e/g r<g/>e <b/>e/g
r8 <g/>e_ <b/>e_/g r <g/>e_ c/e_/b r <f/>d- <b/>d-/e_ r <f/>c <a/>c/f
r8 <f/>d <b/>d/a r <g/>f d/f/g r <g/>e c/e/g r <g-/>e c/e/g-
r8 <f/>e <b/>e/a r <f/>d <b/>a r <g/>e <b/>e/g
V3: o2
r8 e4. >e4. <e4. d4.
c4. >c4. <f4. f4.
b4. b_4. >c4. <a_4. 
b4. <b4. >c4.

**Comment by rolandng01** [comment]
Thank you. Another example.

```alda
(volume! 100)
(key-signature! "e- a- b-")
(tempo! 95)
piano:
V1: o4
{r b >e}4 {g b >e}4 g4. f8 f8. e16 {e d c}4 c4 r
{r <<d f}4 {b >d f}4 >d4. c8 c8. <b16 {b a g}4 g4 r 
{r <b >e}4 {g b >e}4 g4. f8 f8. e16 {e d c}4 c4 r
{r <d f}4 {a >d f}4 {r <g b}4 {>e g b}4
{b>c<b>c<b>c<b>c<b>c<b>c}4
<a_16 b16 >g16. f32 e4
V2: o3
r4 b/>e/g <b/>e/g <b/>e/g
r4 <a/>c/f <a/>c/f <a/>c/f
r4 <f/a/b/>d <f/a/b/>d <f/a/b/>d
r4 <b/>e/g <b/>e/g <b/>e/g
r4 <b/>e/g <b/>e/g <b/>e/g
r4 <a/>c/f <a/>c/f <a/>c/f
r4 <b/>f r <b/>c/e
r4 <b>/d/f/a
V3: o2
e1/>e <a1/>a <b1/>b <e1/>e
<e1/>e <a1/>a <b2/>b <e2/>e
<<b2/>b >e4/b/>e
```
