### ISSUE TITLE
Feature request: export to MusicXML format

### ISSUE THREAD

**Issue by Trevoke** [alda-lang/alda#44]
'Cause that would be awesome.

[ Used to be "export to musescore format" ]

**Comment by kirbyfan64** [comment]
Can't MuseScore import MIDIs??

Wait...

(remembers how MuseScore loves to put 16th notes everywhere when importing MIDIs)

Nevermind.

**Comment by daveyarwood** [comment]
I've used and enjoyed MuseScore -- it's a nice piece of software. However, I think it would be more useful for Alda to export to a common format like [MusicXML](https://en.wikipedia.org/wiki/MusicXML), a format that a wide variety of GUI programs (including MuseScore) can import.

**Comment by Trevoke** [comment]
Sold. Updating original request.

**Comment by daveyarwood** [comment]
:+1:

**Comment by 0atman** [comment]
can MusicXML be converted easily to midi? I bet it can. If so, I'm behind this 100%, two birds with one stone!

**Comment by daveyarwood** [comment]
I believe it is. I'm no expert on MusicXML, but from what I know, it seems like a kind of "lingua franca" that can be used to translate between different musical data formats.

**Comment by 0atman** [comment]
wait, does this work already? http://alda.io/web-demo/

**Comment by 0atman** [comment]
I think this issue is super important. Once we add even basic MusicXML support, we gain a bunch of features for free, for instance: We could go the [music21](http://web.mit.edu/music21/) route and use LilyPond to do much heavy lifting, it's got commandline flags for converting between midi and MusicXML, and can even output score as pngs. I expect it has a bunch of other features that would be easy to integrate. Cross platform too!

**Comment by daveyarwood** [comment]
Our web demo is out of date, and uses a hacked-together JavaScript (via ClojureScript) partial port of Alda 0.6.4. Updating the web demo is a TODO item, but I think would be a lot of effort. It would probably be easier to add MusicXML support to the current version of Alda.

I totally agree that this would be a killer feature! One could also import/export Alda scores to and from GUI score editor programs like Finale and Sibelius. The possibilities are endless.

**Comment by 0atman** [comment]
Ah, got it. 
BTW, here's how music21 looks with LilyPond behind the scenes:
https://gist.github.com/0atman/3b5398eef04f497550560640c90e87ce

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-core/issues/3.
