### ISSUE TITLE
open /tmp/alda-doctor1917232005/1666820313.mid: no such file or directory

### ISSUE THREAD

**Issue by SebAlbert** [alda-lang/alda#458]
# 🐞 Bug report 🐞

## Description
Fresh download, new user.
After problems with the 101 tutorial (`alda repl`), I tried `alda doctor`. It errs out at "Export score as MIDI" after hanging a couple of seconds, and after it errs out, I hear an upward broken major chord and see a persisting java process of alda-player.

## Steps to Reproduce
1. Download current `alda` and `alda-player`, make executable and put on `PATH`
2. Execute `alda doctor`

I am using Gentoo Linux an a laptop with an external soundcard (USB) that does not seem to be used. I have both Pipewire and ALSA installed.

## Expected Behavior
I would hope that the self-test passes. Furthermore, I would not expect remaining Java background processes after exit of the command I launched.

## Actual Behavior
It errs out at "Export score as MIDI" after hanging a couple of seconds, and after it errs out, I hear an upward broken major chord and see a persisting java process of alda-player.

## Environment
**Operating system and version:**
Gentoo Linux, rolling.

**Alda version:**
```
$ alda version
alda 2.2.3
```

```
$ alda-player info
alda-player 2.2.3
log path: /home/seb/.cache/alda/logs
```

**Health check:**
```
$ alda doctor
OK  Parse source code
OK  Generate score model
OK  Ensure that there are no stale player processes
OK  Find an open port
OK  Send and receive OSC messages
OK  Locate alda-player executable on PATH
OK  Check alda-player version
OK  Spawn a player process
OK  Ping player process
OK  Play score
ERR Export score as MIDI

---

Oops! Something went wrong:
  open /tmp/alda-doctor1917232005/1666820313.mid: no such file or directory

This might be a bug. For help, consider filing an issue at:
  https://github.com/alda-lang/alda/issues/new/choose

Or come chat with us on Slack:
  https://slack.alda.io
```

**Logs:**

```
gip INFO  2022-10-26 23:38:33 StateManager.cleanUpStaleStateFiles:72 - Cleaning up stale files in /home/seb/.cache/alda/state/players...
gip INFO  2022-10-26 23:38:33 StateManager.cleanUpStaleStateFiles:72 - Cleaning up stale files in /home/seb/.cache/alda/state/repl-servers...
gip INFO  2022-10-26 23:38:33 Main.run:77 - Starting receiver, listening on port 37209...
gip INFO  2022-10-26 23:38:54 MidiEngine.<init>:276 - Initializing MIDI sequencer...
gip INFO  2022-10-26 23:38:54 MidiEngine.<init>:281 - Initializing MIDI synthesizer...
gip INFO  2022-10-26 23:38:56 Main.run:90 - Starting player...
gip DEBUG 2022-10-26 23:38:56 Parser.parse:238 - received ping
gip DEBUG 2022-10-26 23:38:56 Player.invoke:346 - TRACK 1: startOffset is 0
gip DEBUG 2022-10-26 23:38:56 Player.invoke:349 - eraBefore: 0; eraAfter: 0
gip DEBUG 2022-10-26 23:38:57 MidiEngine.meta:334 - Received Set Tempo meta event
gip DEBUG 2022-10-26 23:38:59 MidiEngine.meta:291 - Received CONTINUE meta event
gip DEBUG 2022-10-26 23:39:00 MidiEngine.meta:291 - Received CONTINUE meta event
gip DEBUG 2022-10-26 23:39:01 MidiEngine.meta:291 - Received CONTINUE meta event
gip DEBUG 2022-10-26 23:39:02 MidiEngine.meta:291 - Received CONTINUE meta event
gip DEBUG 2022-10-26 23:39:03 MidiEngine.meta:291 - Received CONTINUE meta event
```

Afterwards:

```
$ ps aux | grep alda
seb      20347 10.3  0.6 4566324 106200 pts/2  Sl   23:38   0:02 /usr/lib64/icedtea8/bin/java -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -Xmx1024m -Xms256m -DlogPath=tmplog -jar /home/seb/bin/alda-player -v run -p 37209
seb      20387  0.0  0.0   7648  2284 pts/2    S+   23:38   0:00 grep --colour=auto alda
```

**Comment by SebAlbert** [comment]
Thank you for helping me troubleshoot!
I can confirm that the particular .mid file in /tmp actually does exist after the process exited with the error.

Regarding timing, I can also tell that between "OK Play score" and "ERR Export score as MIDI" it seems to be waiting for around 10 seconds.

Furthermore, upon trying again, I do *not* hear the notes being played again unless I execute `alda shutdown` in between.

I could provide an `strace` output if that is of any use. Are there any particular syscalls on which I could filter? I tried `strace -ff -tt -T` and got 79 files (for 79 process IDs), which seems a lot. Also, irritatingly, the first one starts off reading all certificates in `/etc/ssl/certs`.

The process that finally writes the error apparently tries to open the midi file every 200 milliseconds or so, always receiving -1 ENOENT from the kernel.

It may or may not be of interest that /tmp is a tmpfs (RAM disk) on my machine.

When `watch`ing an `ls -laht /tmp/alda-doctor*` from a second terminal, I can see that the directory is created right away, but the MIDI file in it only appears after the `alda doctor` command has exited with the error, seemingly at the same instant when I hear it play.

**Comment by SebAlbert** [comment]
I cloned the repository, doubled the reasonable timeout value from 20 to 40 in `client/src/cmd/doctor.go` and now `go run main doctor` works without an error, however, without the notes playing at all. (Maybe the players are shut down right when the MIDI file is there, which is only when I would be hearing the test notes...)

**Comment by daveyarwood** [comment]
Interesting -- so it must be taking longer than 20 seconds to generate the MIDI. That's not great - I wonder why it takes so long? :thinking: 

The lack of playback (or abrupt stop to playback) during `alda doctor` is expected -- there is a subsequent health check that shuts down the player, so depending on how long the earlier steps take, you might hear partial playback or no playback at all.

**Comment by daveyarwood** [comment]
> When `watch`ing an `ls -laht /tmp/alda-doctor*` from a second terminal, I can see that the directory is created right away, but the MIDI file in it only appears after the `alda doctor` command has exited with the error, seemingly at the same instant when I hear it play.

This is very interesting. No idea why it would behave that way, off hand.

**Comment by daveyarwood** [comment]
Closing this for now - happy to re-open if we can identify a concrete issue to be fixed!
