### ISSUE TITLE
Are there any PORTABLE version of alda that can run without java?

### ISSUE THREAD

**Issue by GhostShadow0316** [alda-lang/alda#460]
Just like the title, I want to use alda in my python script using [this](https://pypi.org/project/alda-python/) library.
Is there any portable version of alda that can let me run it in my python script to run on any computer even don't have alda installed?

**Comment by daveyarwood** [comment]
Hi @GhostShadow0316 , thanks for the question!

In general, Alda libraries for various programming languages will depend on having Alda installed on your system, as this is [the approach that I encourage](https://github.com/alda-lang/alda/blob/master/doc/implementing-an-alda-library.md). There is not (yet?) any portable version of Alda available that can be used without installing the `alda` and `alda-player` binaries.

I am, however, interested in [making Alda run in the browser](https://github.com/alda-lang/alda/discussions/455), and I've been working on that a little bit off and on. I'm not sure if that's close to what you have in mind, but I thought I'd mention it.
