### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by bluebear94** [alda-lang/alda#47]
```
C:\Users\*****\alda>boot alda play --file=test.alda
             clojure.lang.ExceptionInfo: java.lang.IllegalArgumentException: No such task (alda)
    data: {:file
           "C:\\Users\\*****\\AppData\\Local\\Temp\\boot.user5660940546126207748.clj",
           :line 7}
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No such task (alda)
     java.lang.IllegalArgumentException: No such task (alda)
          boot.core/construct-tasks  core.clj:  672
                                ...
                 clojure.core/apply  core.clj:  630
                  boot.core/boot/fn  core.clj:  706
clojure.core/binding-conveyor-fn/fn  core.clj: 1916
                                ...
```

**Comment by daveyarwood** [comment]
I'm sorry you're running into problems... I'm still trying to figure out how Alda and Boot should work for Windows users. 

My recommendation would be to try using the full path to the `alda` executable file, e.g.:

    boot C:\Users\Dave\alda\alda play --file test.alda

Or, if the `alda` file is in the current directory, this ought to be equivalent:

    boot .\alda play --file test.alda

Closing this issue, but I'll be happy to continue the discussion in issue #48.
