### ISSUE TITLE
Refine and document Alda installation/usage on Windows

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda#48]
A large handful of people have noted experiencing problems installing and running Alda in a Windows environment. #47 is a good example of an error that at least 2 other people have noted running into.

Open questions:

- **Is it possible to run a standalone executable Boot script in Windows?**

    The [`alda` executable](https://github.com/alda-lang/alda/blob/master/bin/alda) does start with `#!/usr/bin/env boot`. On OS X, I am able to run `alda` globally by making this file executable and copying it a directory in my `$PATH`. I am also able to run it by running `boot ~/Code/alda/bin/alda`. I can reproduce the "No such task (alda)" issue by cd-ing into ~/Code/alda/bin and trying to run `boot alda`, probably because Boot can't know if `alda` is supposed to be a task or a file. Clarifying that it's a file by running `boot ./alda` fixes it.

- **Can a Windows user simply copy the `alda` executable script into a directory in their path and be able to run `alda` from any directory?**

    Subquestion: Does a file need to be a .exe in order to be added to the path?

- **Why doesn't running `boot D:\path\to\alda` (with boot.exe on the user's path) work?** 

    ... *Does* it work?

Would greatly appreciate any insight from Windows power users, or better yet, Windows users familiar with running Boot. I am a Windows n00b.

**Comment by hstolte** [comment]
Hi @daveyarwood, I get the same error-message as mentioned in https://github.com/alda-lang/alda/issues/47#issue-105146174 and could not find a solution yet.

environment: Windows 7
- ``boot.exe`` in ``C:\Windows\System32``
- alda ``/bin`` in PATH

Here are my observations:

- running ``alda`` from any directory does not work (command not found)
- running ``boot .\alda``, ``boot alda`` or ``boot C:/absolute/path/to/alda`` from the ``/bin`` dir results in the error-message linked above

**Comment by daveyarwood** [comment]
@hstolte thanks for reporting -- this behavior does seem to be consistent with the problems other people are having. I'll bet the problem has to do with `alda` not being a binary executable file -- it's a script with a shebang. 

According to [this StackOverflow answer](http://stackoverflow.com/a/7574585/2338327), Windows has no shebang support *unless you are using [Cygwin](https://www.cygwin.com/)*.

Can someone confirm whether or not Alda works with Cygwin?

If Alda does not work with Cygwin, [it could potentially be an encoding issue](http://superuser.com/a/484053/485305) in the `alda` script.

**Comment by bluebear94** [comment]
The error happens on Cygwin as well.

**Comment by ghoger** [comment]
I'm also hitting the "no such task (alda)" error on Windows. Just wanting to get past this (I want to play w/ Alda! :-) ), I tried running "boot repl" and manually running the commands in the alda task script.

boot.user=> (set-env! :dependencies '[[alda "LATEST"]])
Boot printed messages about retrieving various .jars from clojars.org. No errors. Return value printed was "nil". So far, so good. (I assume. I'm not familiar with Clojure or boot.)

boot.user=> (require '[alda.cli])"
Boot printed just the return value "nil". Again, I assume all is ok.

boot.user=> (defn -main [& args] (apply (resolve 'alda.cli/-main) args))
Boot printed "#'boot.user/-main" (w/o the double-quotes).  OK, again, I think.

But that just defines a function; it doesn't really try to invoke Alda. So I tried a few things (but I don't know what I'm doing here):

boot.user=> alda
boot.user=> (alda)
Both of these gave me an error like: "CompilerException java.lang.RuntimeException: Unable to resolve symbol: alda in this context,...".

boot.user=> (-main)
This gave me the following:
alda v0.4.5

Usage:

    alda <task> <options>

To see options for a task:

    alda <task> --help

Tasks:

    help        Display this help text.
    version     Display Alda version number.
    play        Parse some Alda code and play the resulting score.
    parse       Parse some Alda code and print the results to the console.
    repl        Starts an Alda Read-Evaluate-Play-Loop.
nil

Obviously, it is actually running Alda, so I think I'm getting close. However, I don't know how to pass arguments to alda. I tried a few things but kept getting: MissingFormatArgumentException Format specifier '%s'  java.util.Formatter.format (:-1)

Having gotten this far, how can I inoke, say, the alda repl task from here?

**Comment by daveyarwood** [comment]
@ghoger Arrrgh, so close! :confounded:

What you did from the Boot REPL all looks correct -- basically, as you've figured out, it should do exactly what the `alda` script does.

BTW, that `-main` function takes a variable number of arguments, which are passed in automatically by your shell when you run the script. For example, you should be able to play an Alda score from a file like this:

    (-main "play" "--file" "D:\path\to\your\score.alda")

I've never seen that Java warning before... were you able to use the REPL OK after that?

---

By the way, everyone, I think I may have a workaround to use Alda if you're a Windows user. Try this:

```
git clone -b boot-alda-task git@github.com:alda-lang/alda.git
cd alda
boot alda -x 'play --code "piano: g16 g8 g d+16 e8 c r > c"'
boot alda -x repl
```

Let me know if the above works! It's not ideal for a couple of reasons\*, but hopefully it should at least let you in so you can start playing around with Alda. I'll keep this issue open in the meantime -- I'd like to see if there is a way Windows users can use the `alda` executable instead of this workaround.

\* 1) The `-x '<cmd> <args>'` syntax is a little cumbersome. 2) It doesn't automatically update you to the latest version of alda like the `alda` script does.

**Comment by ghoger** [comment]
@daveyarwood Thanks for the reply. I was able to use Alda repl task invoked from within boot via
`boot.user=> (-main "repl)`

I was also able to do `(-main "play" "--file" "C:\path\to\my\score.alda")`. But it worked only the first time per session. Subsequent tries gave me an error. (Something about Java Midi something or other. Sorry, I don't have my laptop in front of me right now. I got the impression that it might just be that the "play" task possibly fails to release some Java resource/handle related to the Midi support causing subsequent runs to not be able to allocate it. Or something like that. Which probably wouldn't be an issue under normal usage in which the alda script would run just one task and exit. I'll try to remember to get the full error message/text this evening.) To make it work again I have to exit boot and even close the command window.

I haven't tried the workaround yet. Hopefully, this evening.

**Comment by daveyarwood** [comment]
@ghoger If this is the error you're referring to, I'm able to reproduce it:

```
java.util.concurrent.ExecutionException: javax.sound.midi.InvalidMidiDataException: cannot get soundbank from stream
javax.sound.midi.InvalidMidiDataException: cannot get soundbank from stream
```

I think it has something to do with not being able to load the instruments from the FluidR3 soundfont over again. If you choose not to load FluidR3 by adding a `"--stock"` argument to the `(-main "play" ...)` call, the error goes away (but then, you don't get the nice sound of the FluidR3 soundfont).

At any rate, you're right, the `alda play` task is not meant to be used from the REPL like this.

Fingers crossed that my workaround works!

**Comment by ghoger** [comment]
1. Yes, "cannot get soundbank from stream" is the error I was getting trying to run multiple alda tasks from w/i the same boot repl.
2. The workaround at least partly worked for me. Doing `boot alda -x repl` got me the ">" prompt, I could enter Alda code, and it played fine.

However, `boot alda -x 'play --code "piano: g16 g8 g d+16 e8 c r > c"'` did not work. I got:
```
             clojure.lang.ExceptionInfo: java.lang.IllegalArgumentException: Unknown option: "--code"
    data: {:file
           "C:\\Users\\gary\\AppData\\Local\\Temp\\boot.user7353093096119766079.clj",
           :line 17}
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Unknown option: "--code"
     java.lang.IllegalArgumentException: Unknown option: "--code"
          boot.core/construct-tasks  core.clj:  669
                                ...
                 clojure.core/apply  core.clj:  630
                  boot.core/boot/fn  core.clj:  699
clojure.core/binding-conveyor-fn/fn  core.clj: 1916
                                ...
```

**Comment by daveyarwood** [comment]
@ghoger We're one step closer -- I learned just now that the Windows command line doesn't like single quotes, so if you need to nest quotes like in this example, you have to use double-quotes and escape the inner quotes. This ought to do the trick:

    boot alda -x "play --code \"piano: g16 g8 g d+16 e8 c r > c\""

**Comment by ghoger** [comment]
The escaped double-quotes didn't work for me. But nesting single-quotes w/i the double-quotes did work:
`boot alda -x "play --code 'piano: g16 g8 g d+16 e8 c r > c'"`
So I seem to be in business. Thanks!

**Comment by daveyarwood** [comment]
Awesome! I'm so glad that we have a workaround.

I will document the workaround in the Alda README, but will keep this issue open until we can find a better way... I know there has to be a way for Windows users to run the Alda script!

**Comment by ghoger** [comment]
Just a little more info on the WindowsPreferences (init) error:
```
Sep 09, 2015 7:39:33 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
```
A bit of googling turned up [this IBM Technote](http://www-01.ibm.com/support/docview.wss?uid=swg21496098) about it. I'm using Sun/Oracle Java, not IBM's, but the problem seems to be cross-vendor and the suggested solution worked for me. Of course, that begs the question of why Java  tries to create/use an incorrect registry key, but, hey, one thing at a time, eh? :-)

**Comment by pkobrien** [comment]
I'm really looking forward to playing with Alda. Just wanted to say hello and mention that I have experience with Clojure and Boot, and I'm on Windows, so I will try to help resolve any Windows issues with Alda. I've created a fork and am patiently waiting for the download of fluid-r3 to finish. :-)

**Comment by crisptrutski** [comment]
@pkobrien good to see you here! Looking forward to that L-system algorave :speaker:

**Comment by pkobrien** [comment]
@crisptrutski Thanks! Good to see you here as well. Seems to be rather popular. I'm hoping to have a sampling of L-system experiments today. We'll have to schedule an Aldarave some time. ;-)

**Comment by pkobrien** [comment]
I can confirm that the following command works fine on Windows and sounds quite nice:

boot alda -x "play --file test/examples/awobmolg.alda"

**Comment by daveyarwood** [comment]
@pkobrien Awesome - that would be super helpful! Welcome to the party! :balloon: 

Do you know anything about running shebang scripts on Windows? Is it possible to do?

**Comment by mforzano** [comment]
I was able to get it working (somewhat) with Cygwin. On the first line of the script I changed 'boot' to 'boot.exe', after which ./alda worked. The REPL doesn't seem to work, though. Nothing happens when I type commands, and when I exit the application I can see that the commands were passed to the shell rather than the boot application.
I'm able to play text files without any issues. I had the registry key issue mentioned above but the suggested fix worked for me.

**Comment by jjgh** [comment]
Can someone make a list of steps needed in order to install it on Windows? 
Thanks!

**Comment by daveyarwood** [comment]
Just an update on this: We're working on making Alda a standalone executable program instead of a script like it is now. This should make it a lot easier to run. Then we should be able to use [Launch4j](http://launch4j.net) to generate an `alda.exe` file, which you should be able to place in your `C:\Windows\System32` directory and then I think you should be able to run `alda` from anywhere, just like Unix users.

**Comment by daveyarwood** [comment]
Windows users: I'm working out the details of generating a standalone executable for Alda with each release. I think I'm close!

I created this using Launch4j: https://github.com/alda-lang/alda/releases/download/0.14.0/alda.exe

Could you all take a minute and download alda.exe and try it out? You should be able to run it with the usual command line arguments, i.e.:

```
alda.exe version
alda.exe repl
alda.exe play --code "piano: c8 d e f g"
```

And I think if you move alda.exe to any folder in your [path](http://www.computerhope.com/issues/ch000549.htm), you should be able to run Alda from any directory like this:

```
alda version
alda repl
alda play --code "piano: c8 d e f g"
```

Please let me know if this works -- I know very little about Windows, but I want to get it working for you guys!

**Comment by jjgh** [comment]
Quick feedback: it's working but I think but midi events should be synchronized (I think this should be handled by the midi library by default..?) otherwise notes won't respect duration and even in a chord notes will play off sync!

**Comment by daveyarwood** [comment]
@jjgh -- This is an issue I observed with the Unix executable as well. I think since we're not waiting for the MIDI soundfont to load, the buffering problems we already have (see #26) are made even more obvious. Basically, Alda starts trying to play the score before all the notes are scheduled.

1) Could you try this for me?

```
alda play --pre-buffer 5000 "piano: c8 d e f g"
```

2) Do you notice the same timing issues in the Alda REPL?

**Comment by jjgh** [comment]
@daveyarwood I see. I tried with `--pre-buffer` but I get no sound output at all. And the same happens with just: `alda play "piano: c8 d e f g"` but I didn't notice this before because I went straight into the repl.

**Comment by daveyarwood** [comment]
Oops -- I left out something important! Try this:

    alda play --pre-buffer 5000 --code "piano: c8 d e f g"

It's interesting that you're hearing timing issues in the REPL... I'm not sure what the issue could be there. It could just be a performance issue, though I don't think Alda is too terribly performance-intensive to run.

**Comment by jjgh** [comment]
@daveyarwood alright! Now everything seems to be perfectly timed! About the REPL performance issues, I don't know, but nor CPU or RAM is the bottleneck here..

**Comment by daveyarwood** [comment]
That's awesome! You can try decreasing 5000 ms to a smaller number, so you won't have to wait a full 5 seconds every time you want to play a score. The "right number" varies from system to system, as well as from score to score. You can figure out a good number by trying smaller numbers until you start to hear timing issues again. You may be able to get away with a pre-buffer as small as 500-1000 ms. (Hopefully in the near future we'll get smart buffering implemented so you don't have to worry about setting this number.)

The REPL timing issues are concerning, but at any rate, I'm so glad this works! Definitely a step in the right direction.

**Comment by jjgh** [comment]
:+1: it is! :) I'm glad too. Yes the REPL thing is a bit worrying because without it working I am going to get sucked into JVM startup times sinkhole :) which can be as harming as GUI distraction ;)

**Comment by daveyarwood** [comment]
@jjgh I totally agree. Luckily, I think #49 will be in the works soon, which will get around the JVM/Clojure startup issue by having Alda run in the background as a server, so it can respond immediately when you give it commands. Having a fast feedback loop is definitely high on my list of priorities!

**Comment by jjgh** [comment]
@daveyarwood great to hear that! :+1: :+1: :+1:

**Comment by daveyarwood** [comment]
One caveat with the `alda.exe` file that I linked above is that inline Clojure code (including attributes like `tempo`, `volume`, etc.) does not work properly. This is not a Windows-specific issue, but a general issue that has to do with running Alda in a self-contained file instead of via Boot (which we currently rely on for the inline Clojure code functionality). We'll be making tweaks to how we create the executables (see the end of #92 -- basically, we will package Boot into alda.exe) that should solve this issue.

**Comment by daveyarwood** [comment]
The changes described above are coming soon -- with the upcoming 1.0.0-rc1 release candidate, Windows users will have an alda.exe to play around with. This release candidate will include the server/client relationship with Alda running in the background, which will hopefully help with some of the timing issues. I'm sure there will continue to be issues, which I'll be happy to keep tracking and see what we can do. Windows support can be tough!

**Comment by daveyarwood** [comment]
Windows friends: please give the [alda v1.0.0-rc1](https://github.com/alda-lang/alda/releases/1.0.0-rc1) a try when you have a minute. After downloading `alda.exe` and making it available on your system root path (`move alda.exe %SystemRoot%`), you should be able to run the following commands:

```
# wait for server to start, then play some code
alda play -c "oboe: (tempo! 150) c8 d e f g"

# play some more code (without waiting for the server to start!)
alda play -c "a b > c d e d c4."

# display server status
alda status

# display server version
alda version

# stop the server, if you want
alda stop

# start a repl (takes a while... this will be improved in the near future)
alda repl
```

Please let me know if you find any issues -- you can either keep commenting here, or create a new issue.

Hoping to have a solid foundation of Windows support for Alda by version 1.0.0!
