### ISSUE TITLE
No way to download Alda 2

### ISSUE THREAD

**Issue by childoftheabyss** [alda-lang/alda#486]
# 🐞 Bug report 🐞

## Description
Hello, I found this project very interesting and I was looking to download it, however the website has no download link (https://alda.io/install/) besides asking to install the OpenJDK. On Github, in releases, only the 1.* version is available as a binary. I was able to clone the repo and build both the player and client from source code (tag 2.2.5), but I don't think this workflow is intentional.

I did look in documentation to see if I was missing something but I was not able to find any notice about this.

## Steps to Reproduce

1. Go to https://alda.io/install/, no link to download in Step 2.
2. Go to this repository in releases page, the latest compiled release is still 1.5.0.

N/A

N/A

Maybe I missed a big download button somewhere, so tell me if I made a mistake. I found this blog post from the author from 2021 announcing Alda 2 (https://blog.djy.io/announcing-alda-2/), so I was expecting a binary release.

## Expected Behavior

I should be able to download the compiled program for Alda 2.

## Actual Behavior

I can´t find any way to download the compiled Alda 2.

## Environment

N/A

**Operating system and version:**
N/A

**Alda version:**

```
$ alda version

```
N/A

```
$ alda-player info

```
N/A

**Health check:**

```
$ alda doctor

```
N/A

**Logs:**

```
```
N/A

**Comment by daveyarwood** [comment]
Hi, thanks for reporting this!

Can you check the install page again? I think there may have been a temporary glitch. I went there just now and I do see download links:

![Screenshot 2023-07-19 at 18-33-24 Install](https://github.com/alda-lang/alda/assets/4909079/0ce9e676-1e08-4acc-8721-009b04d975ca)

**Comment by childoftheabyss** [comment]
Hi,
thank you for your quick response. I realized it was totally my mistake! I didn't realized no-script was running in my browser, I disable it and now I can see it. Sorry for wasting your time.

Anyway, on Github it wouldn't be better to have the 2.2.5 release here instead of 1.5.0?
![image](https://github.com/alda-lang/alda/assets/75948189/e9a1347d-4a5d-4f83-b99c-d781cf8dec89)

Thank you again and sorry again. Now I can play around with Alda!

**Comment by daveyarwood** [comment]
Starting with Alda 2.0.0, releases are no longer hosted in GitHub. That final 1.x release is there because it has the ability to update itself to the latest Alda 2.x release. The idea was to make it easy for Alda users to update to Alda 2.x back when it came out in 2021.

I do think it's confusing that the latest GitHub release appears to be an old one from 2 years ago. Maybe it would be worth removing all of the old 1.x releases from GitHub at this point. 🤔

**Comment by daveyarwood** [comment]
I deleted all of the old Alda 1.x releases just now, to avoid confusion. To install the latest version of Alda, go to https://alda.io/install and follow the instructions there.
