### ISSUE TITLE
cannot run alda

### ISSUE THREAD

**Issue by waldolin** [alda-lang/alda#488]
# 🐞 Bug report 🐞
alda doctor
OK  Parse source code
OK  Generate score model
Aug 31 11:05:42 WRN cmd/doctor.go:138 > Failed to reach player process. Deleting state file. error="dial tcp 127.0.0.1:53099: connectex: No connection could be made because the target machine actively refused it." player={"Expiry":1693451536038,"ID":"xcc","Port":53099,"State":"ready"}
Aug 31 11:06:03 WRN cmd/doctor.go:138 > Failed to reach player process. Deleting state file. error="dial tcp 127.0.0.1:53100: connectex: No connection could be made because the target machine actively refused it." player={"Expiry":1693451522927,"ID":"xpa","Port":53100,"State":"ready"}
Aug 31 11:06:25 WRN cmd/doctor.go:138 > Failed to reach player process. Deleting state file. error="dial tcp 127.0.0.1:53098: connectex: No connection could be made because the target machine actively refused it." player={"Expiry":1693451322413,"ID":"zxg","Port":53098,"State":"ready"}
OK  Ensure that there are no stale player processes
OK  Find an open port
OK  Send and receive OSC messages
OK  Locate alda-player executable on PATH
OK  Check alda-player version
OK  Spawn a player process
OK  Ping player process
OK  Play score
OK  Export score as MIDI
OK  Locate player logs
OK  Player logs show the ping was received
OK  Shut down player process
OK  Spawn a player on an unknown port
OK  Discover the player
OK  Ping the player
OK  Shut the player down
OK  Start a REPL server
nREPL server started on port 53272 on host localhost - nrepl://localhost:53272
OK  Find the REPL server
OK  Interact with the REPL server
OK  Shut down the REPL server

alda doctor
OK  Parse source code
OK  Generate score model
OK  Ensure that there are no stale player processes
OK  Find an open port
OK  Send and receive OSC messages
OK  Locate alda-player executable on PATH
OK  Check alda-player version
OK  Spawn a player process
OK  Ping player process
OK  Play score
ERR Export score as MIDI

---

Oops! Something went wrong:
  EOF

This might be a bug. For help, consider filing an issue at:
  https://github.com/alda-lang/alda/issues/new/choose

Or come chat with us on Slack:
  https://slack.alda.io

## Description

1.can not visit   https://slack.alda.io to chat
2.can not use alda 
it can be used before.
3.i have added the path  C:\Users\lin\Downloads\alda into environment variable
it still cannot work
4.i open cmd
start alda.exe
it can not type anything on the command
5. i run alda doctor two times
6. can not open .alda file
7. 
## Steps to Reproduce

1.
2.
3.
4.

## Environment

window 11

**Operating system and version:**
Alda 2.2.6 (2023-08-19)
java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

**Alda version:**

```
$ alda version

```

```
$ alda-player info

```

**Health check:**

```
$ alda doctor

```

**Logs:**

```
```

**Comment by daveyarwood** [comment]
Hi @waldolin , thanks for reporting this!

I'm curious if this problem happens consistently. Can you try running `alda doctor` a couple more times and tell me if the same problem keeps occurring every time?

**Comment by waldolin** [comment]
> Hi @waldolin , thanks for reporting this!
> 
> I'm curious if this problem happens consistently. Can you try running `alda doctor` a couple more times and tell me if the same problem keeps occurring every time?

Hi, i run alda doctor 
And it can run as usual,
I really don't know what is the problem? 

But i occur a problem when using vsc to  output .mid
But it can be outputed on cmd...
alda export -f /tmp/parts.alda -o /tmp/parts.mid
And i use the same 
./alda export -f /tmp/parts.alda -o /tmp/parts.mid
It can not be able to work.
It can be played on vsc.

**Comment by daveyarwood** [comment]
Great! I'm glad you figured it out :+1:
