### ISSUE TITLE
Can i generate an mp3 with my code?

### ISSUE THREAD

**Issue by song-without-words** [alda-lang/alda#493]
# 🔧 Feature request 🔧

**Comment by daveyarwood** [comment]
Hi @song-without-words! This is something we've discussed in the past, and while there is no current plan to support exporting to mp3 in a built-in way, it is still possible to do it by using Alda to export to MIDI, and then use Fluidsynth to convert the MIDI file into an mp3 (or wav or whatever audio file type you prefer)

See: https://github.com/alda-lang/alda/discussions/434#discussioncomment-3824875

**Comment by daveyarwood** [comment]
To clarify: I wouldn't be opposed to adding this as a built-in feature at some point, it's just that there is no immediate plan to do so. If someone wanted to contribute this feature, I would be happy to support them in any way that I can.

**Comment by song-without-words** [comment]
thanks for your reply.
