### ISSUE TITLE
Alda could use a better logo

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda#50]
You can see our current logo here: https://github.com/alda-lang

It's something I hacked together in GIMP late one night because I was tired of looking at the default org logo generated by GitHub.

What I would love, though, is for someone with better graphic design skills than I to come up with something more pleasing to the eye. 

I'm thinking something that doesn't have the word "alda" on it. Maybe some kind of stylized "A"? The name Alda comes from the Quenya word for "tree," so something tree-related might be cool, but that's not a requirement.

**Comment by kirbyfan64** [comment]
What about something with the full word "alda", but with one of the letters replaced with a musical note? For instance, maybe the "d" could be a quarter note.

**Comment by daveyarwood** [comment]
That could be cool -- I'm open to that.

**Comment by Omega9** [comment]
What about [tengwar](http://www.omniglot.com/conscripts/tengwar.htm)?
There's a whole letter means 'tree' -
![](http://tolkiengateway.net/w/images/c/c6/Alda.gif)

**Comment by daveyarwood** [comment]
I'm not sure I like that aesthetic. There might be copyright issues with using tengwar, as well.

**Comment by ErikPettersson** [comment]
Maybe something techy-musicy along these lines:

![alda-logo-2](https://cloud.githubusercontent.com/assets/75019/9723263/bae103ac-55bd-11e5-9bf2-2ed700e80820.png)


Would need to redraw it so it's sharper and more proper waveformy (like that Joy Division cover), could also be colored something like https://commons.wikimedia.org/wiki/File:Spectrogram_of_violin.png if one wanted.

Any interest in that?

**Comment by daveyarwood** [comment]
@ErikPettersson Yes -- I like where this is headed! I like the spectrogram idea.

BTW, I'm going to leave this issue open for a while, but please feel free to submit anything you might come up with -- it's much appreciated!

**Comment by ErikPettersson** [comment]
![alda-logo-3](https://cloud.githubusercontent.com/assets/75019/9773010/13f7a7ec-5740-11e5-8ad2-c70f2c94aa81.png)

**Comment by ErikPettersson** [comment]
![alda-logo-4](https://cloud.githubusercontent.com/assets/75019/9773308/cf1a0afa-5741-11e5-9bcf-963b28b9efd8.png)

**Comment by kirbyfan64** [comment]
@ErikPettersson That looks really cool, though I *still* think a quarter note for a `d` would be cool...

**Comment by Far0s** [comment]
That spectogram A is very cool.

**Comment by TheMuphynMan** [comment]
I've played around with this idea for a long time and I came up with this rough concept icon. I hope you like it; I was struggling to come up with something original until I realized that the lower case "a" (for Alda of course) actually lends itself nicely to creative freedom and the image of a tree i wanted to implement, and so going along with that "tree" inspiration i've dangled a leaf from the "a". In my mind it best captured as many ideas surrounding the language of Alda as possible while staying minimal and aesthetically pleasing.

-cheers

![protoaldaicon](https://cloud.githubusercontent.com/assets/7104866/9895595/43f1bf78-5bff-11e5-8634-6017324384fb.png)

**Comment by daveyarwood** [comment]
@TheMuphynMan I like where this is headed!

**Comment by daveyarwood** [comment]
So @ErikPettersson, I do still really like this spectrogram concept, it's just that it hasn't quite "grabbed" me yet in a way that makes me want to make it Alda's official logo immediately. Would you be up for iterating on this idea a little bit? 

I think maybe the capital A isn't doing it for me. Perhaps a lowercase A, or even the whole (lowercase) word `alda`?

**Comment by ErikPettersson** [comment]
![alda](https://cloud.githubusercontent.com/assets/75019/10494600/857b120e-72b7-11e5-9f06-8b8b5eb2dad8.png)

This is fairly unrelated to any requests, but I'm throwing it in anyways.

**Comment by lazho** [comment]
@Hom-Tanks So something like this??
![43f1bf78-5bff-11e5-8634-6017324384fb](https://cloud.githubusercontent.com/assets/2417212/15763800/3b5f43ea-28db-11e6-98f6-32eb0163b9f6.png)

**Comment by Hom-Tanks** [comment]
Has my vote :p

**Comment by benoid** [comment]
Maybe an eighth note shaped like a lower case A?

Here is a quick sketch of the idea:

![alda_sketch](https://cloud.githubusercontent.com/assets/10873598/19138204/129b20a8-8b48-11e6-88ab-0b22d26e055a.png)

**Comment by daveyarwood** [comment]
I like it!

**Comment by benoid** [comment]
I just made an inkscape rendering of it.

![alda](https://cloud.githubusercontent.com/assets/10873598/19141167/f552fb60-8b60-11e6-9967-b696c7fdecbf.png)

**Comment by elyisgreat** [comment]
I don't know why, but this logo seems a bit inappropriate looking to me. I also find that the 8th note and "a" don't stand out as much.

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-lang.github.io/issues/6.
