### ISSUE TITLE
git clone git@github.com:alda-lang/alda.git gives me an error

### ISSUE THREAD

**Issue by q2dg** [alda-lang/alda#51]
This:

*Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.*

I'm using Fedora 22 64 bits, with Boot installed doing
*mv boot.sh boot && chmod a+x boot && sudo mv boot /usr/local/bin && boot -h*

**Comment by kirbyfan64** [comment]
Try instead:

```
git clone https://github.com/alda-lang/alda.git
```

**Comment by q2dg** [comment]
YES!! Thanks!!!

Maybe Readme.md should be modified, then...
