### ISSUE TITLE
How to run this on Windows

### ISSUE THREAD

**Issue by jpruiz114** [alda-lang/alda#56]
I just installed boot as suggested on Windows, not sure what else do I need to run this on Windows.

![image](https://cloud.githubusercontent.com/assets/4614970/9725498/95c7b5be-55ab-11e5-997b-2fdc2ee01c50.png)

Any suggestions?

Thanks,

**Comment by daveyarwood** [comment]
Hi,

We're gradually figuring out how to make Alda Windows-friendly. I feel like we're almost there -- maybe you can help, if you happen to have any insights. Please see the discussion at issue #48
