### ISSUE TITLE
Variation in the time of interpretation

### ISSUE THREAD

**Issue by jeisoncg** [alda-lang/alda#57]
Only it happens when he goes as an argument.
"bin/alda play --code "piano: c6 c6 c6 c7 c7 c7 o3 p1 o3 o3 d12 e6 g12~4"

**Comment by daveyarwood** [comment]
:confused: :question: 

I'm not following. Could you elaborate on the problem?  I tried running your code, but it failed due to `p1` not being valid Alda syntax.

**Comment by jeisoncg** [comment]
Sry, change p1 ->  ">"

**Comment by daveyarwood** [comment]
This sounds alright to me. Does it not sound like you expected?

**Comment by jeisoncg** [comment]
Starting, usually a slight delay .

**Comment by daveyarwood** [comment]
Oh, I see -- this is a known issue that has to do with Alda being a Clojure project. It can take as long as 5-10 seconds to start sometimes. We do have some ideas to get around this, like running Alda in the background as a daemon (see #49)

For now, if you'd like to play around with Alda without having to deal with the startup time issue, you can use the REPL: `bin/alda repl`
