### ISSUE TITLE
octave-change direction by "<" / ">" should be explicitly defined in BNF

### ISSUE THREAD

**Issue by g200kg** [alda-lang/alda#59]
This confusion often occurs in MML-based language

**Comment by daveyarwood** [comment]
I like the idea of explicitly defining `octave-up` and `octave-down` tokens in the grammar. a Pull Request on this would be greatly appreciated (you would become Alda contributor #4!)

**Comment by daveyarwood** [comment]
[alda.parser](https://github.com/alda-lang/alda/blob/master/src/alda/parser.clj) should also be updated to generate the appropriate code for those tree nodes -- it would be more elegant than the current code, which explicitly checks whether the body of the node is ">" or "<"

**Comment by crisptrutski** [comment]
Whoops, should have used `closes` not `refs`
