### ISSUE TITLE
Export to WAV, MP3

### ISSUE THREAD

**Issue by checkraiser** [alda-lang/alda#62]
Hi.

I can play alda file, but how can i export the sound into .MIDI / Mp3 file ?
Thank you.

**Comment by daveyarwood** [comment]
Hi @checkraiser ,

This is a planned feature -- I'll keep this issue open until we've implemented it.

Sorry for the inconvenience!

**Comment by kirbyfan64** [comment]
FWIW, you could probably just export to only MIDI and use [Timidity](http://timidity.sourceforge.net/) for the rest.

**Comment by daveyarwood** [comment]
@kirbyfan64 That's not a bad idea. However, Alda will eventually support combining different types of instruments (MIDI vs. waveform oscillator vs. sampled instrument) into a single score, so being able to export to wav is probably our biggest prerogative. 

Being able to export to MIDI (excluding non-MIDI instruments) would be a nice feature too, though.

**Comment by 190n** [comment]
+1

**Comment by daveyarwood** [comment]
Gathering info for export to wav:

There does not exist, as far as I can tell, a Clojure library to capture the sound output of the current program and export it to wav. But it does appear to be possible, via Java inter-op. This would be a good potential opportunity to build a simple open-source Clojure library for exporting to wav, which we could use in Alda.

Some links, for reference:

* http://stackoverflow.com/questions/23551594/clojure-java-class-casting (the question is how to implement JavaSoundRecorder in Clojure)
* http://stackoverflow.com/questions/11157289/in-java-how-do-i-record-the-sound-output-that-is-going-to-the-speakers
* http://docs.oracle.com/javase/tutorial/sound/accessing.html
* http://www.codejava.net/coding/capture-and-record-sound-into-wav-file-with-java-sound-api

Once we have a way to export to wav, we can shell out to a CLI tool like [LAME](http://lame.sourceforge.net/using.php) to convert to MP3. I think it would be cool to have some degree of this built-into Alda, so it will be extra convenient for users to export scores as mp3s. Something like `alda export --file /path/to/score.alda --output /path/to/score.mp3`, with optional additional flags to specify compression type/quality would be awesome. We could look at the extension of the output file to determine whether the user wants to convert to mp3.

On my wish list is the ability to export to wav/mp3 without also playing the score and having to wait for it to finish playing, but I think that would be pretty hard to implement. I'd be interested, if anyone has any ideas on how to do that.

**Comment by daveyarwood** [comment]
This might be the ticket: https://github.com/bluenote10/gervill/blob/master/src/main/java/Midi2WavRender.java

**Comment by 190n** [comment]
I don't think it needs to have MP3 export -- if it can export to WAV, most programs can already play it, and people can convert it into any other format.

**Comment by elyisgreat** [comment]
Agreed. Raw audio, on the other hand, is another story (although I'm not sure the file format for raw audio. I do know that Audacity, for example, can deal with uncompressed audio). 

Also Don't forget about MIDI export (#145)

**Comment by elyisgreat** [comment]
We should probably combine exporting into a single issue...

**Comment by 190n** [comment]
I know WAV is uncompressed, but I'm not sure if it's considered "raw". I think a lot of audiophiles use FLAC (Free Lossless Audio Codec) for really high-quality audio.

**Comment by daveyarwood** [comment]
From an implementation perspective, I think exporting to MIDI and exporting
to WAV are two separate issues, which will need to be solved in different
ways. So, I would rather keep the two issues separate.

I agree about exporting to mp3 not being necessary as a feature of Alda.
Using LAME on the command-line to do the conversion is easy enough.

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-sound-engine-clj/issues/2.

**Comment by yuanzhiqian** [comment]
still not ready yet?
