### ISSUE TITLE
Third tone is alway to short?

### ISSUE THREAD

**Issue by KochC** [alda-lang/alda#63]
My problem is, that the third tone is alway played just for the half time.

I got an easy example here.  

the `e2`, should normaly be a `e4` (a quarter tone) or in that case just a `e` right? But I have to asign it with a `e2` so it is played like a `e4`.
Is my code wrong or what is the problem here?
```
(tempo! 200)
piano:
  o3
  c4 d4 e2 f4 | g2 g |  a4 a a a | g1   |
  a4 a a a    | g1   |  f4 f f f | e2 e |
  d4 d d d    | c2 c/e/g/>c |
```

**Comment by crisptrutski** [comment]
Very strange - I was unfortunately not able to reproduce it playing the piece from the REPL or the command line on my own machine.  Does the issue affect the same note if you double or halve *all* the durations, or switch the tempo?

**Comment by KochC** [comment]
I fixed the problem with prepending this to my script.
```
a4 a a a
r1
```
but these four tones are strange. So its alwas the third and fourth which are crazy.
durtion or speed dose not affect it.
Maybe I do a video later to show the problem.

My configuration is:
OS X 10.10.5
Java Version: 1.7.0_79
Boot App Version: 2.2.0
Boot Lib Version: 2.2.0
Clojure Version:  1.7.0

**Comment by crisptrutski** [comment]
Perhaps it's a buffering issue - you might want to take a look at #26

**Comment by daveyarwood** [comment]
This does sound like a potential buffering issue -- I am unable to reproduce the problem on my machine.

@KochC Could you try playing it with a little buffering added in via the `--pre-buffer` flag? Something like this:

(assuming your score is saved as `~/score.alda`)

    alda play --pre-buffer 3000 --file ~/score.alda

If that fixes it, then buffering is definitely the culprit -- this is something we will hopefully fix with "smart buffering" as proposed in issue #26

**Comment by KochC** [comment]
@daveyarwood 
fixed it with the ```--pre-buffer```.
Thanks alot ;)
