### ISSUE TITLE
Run alda REPL from Clojure REPL

### ISSUE THREAD

**Issue by crisptrutski** [alda-lang/alda#68]
Not sure if you've got a fancy way to do this, but when hacking on the code base I'd really like to be able to live-update a running alda REPL (or at least be able to launch a fresh one in negligible time)

Tried running the `start-repl!` command from a `boot repl` or cider jack-in process, and in both cases it just blocks without reading input from anywhere sensible.

Guessing that we just need a way to override / use the existing `reader`? Or have you got another approach that already works?

What I'm doing for now: `boot watch build-jar`, and running the regular binary

**Comment by daveyarwood** [comment]
I am able to start an Alda REPL from `boot repl` mostly without problems:

    $ boot repl -n alda.cli
    
    alda.repl=> (start-repl!)

Things get slightly weird if you then exit that Alda REPL and start a new one using `(start-repl!)` -- the `> ` prompt doesn't initially appear, but then appears when you press Enter.

Maybe this is a cider issue?

**Comment by crisptrutski** [comment]
Had tried without emacs in the mix, but could have been iterm2 or nrepl middleware messing things up. Good to know this can work, I'll give it another shot

**Comment by daveyarwood** [comment]
@crisptrutski Any updates on this?

**Comment by crisptrutski** [comment]
Have not attempted it since, will give it a whilr now

**Comment by crisptrutski** [comment]
Totally usable - only note would be it would be cool to refactor the REPL loop itself slightly to enable hot-reloading. For that one case killing inner-REPL and reloading is not too painful at all though
