### ISSUE TITLE
REPL and command line don't play the same

### ISSUE THREAD

**Issue by viking** [alda-lang/alda#70]
Running this from the command line:

    bin/alda play -c "midi-synth-drum: c4 r8 c16 c r8 c r c c4 midi-woodblock: c c c c c"

doesn't sound the same as pasting this into the REPL:

    midi-synth-drum: c4 r8 c16 c r8 c r c c4 midi-woodblock: c c c c c

The command line version is incorrect. There is a weird stutter step that seems to happen.

**Comment by daveyarwood** [comment]
Thanks for reporting -- I think this might be a buffering issue. They sound the same on my machine, which is pretty high-powered (mid-2014 Macbook with a 2.2 GHz Intel Core i7 processor), but it's totally possible for other machines to still be buffering the notes while the audio starts playing, resulting in a stutter. 

We're working on a fix (#26) that will intelligently add more buffer time if your system needs it, and wait to start playing until it's buffered enough. Until that's rolled out, though, you can manually add buffering by adding a `--pre-buffer` flag, with an argument in milliseconds.

Try this:

    bin/alda play --pre-buffer 3000 -c "midi-synth-drum: c4 r8 c16 c r8 c r c c4 midi-woodblock: c c c c c"

This adds a 3-second pause before playback starts, during which time the notes are buffering. If it sounds alright like this, you can decrease the number until playback starts sounding weird, and that should give you a pretty good idea of what length pre-buffer your system needs. You may need to increase the buffer time if it still sounds weird with `--pre-buffer 3000`.

Let me know if adding a pre-buffer helps... if not, then there must be some other problem.

**Comment by MadcapJake** [comment]
Adding the pre-buffer helps my machine quite a bit!  I will be adding a pre-buffer option to the `language-alda` settings (for use with `atom-build`).

**Comment by viking** [comment]
That did the trick. Thanks!

**Comment by daveyarwood** [comment]
:saxophone: :notes:
