### ISSUE TITLE
Startup time

### ISSUE THREAD

**Issue by Strikingwolf** [alda-lang/alda#74]
Is there a way you could fork a background process to lower the startup time? I've been considering making an online interpreter website for this lang, but if I can't send/play the music effectively on the client without egregious startup times for an online interpreter it won't work

**Comment by daveyarwood** [comment]
We have had this very idea -- see #49 

I'd be very interested in hearing more about your ideas about making an online interpreter website! You should join the discussion in issues #72 (using JS/Web Audio API for sound) and/or #73 (transmitting audio from server to client over a WebSocket)
