### ISSUE TITLE
Overlapping notes with same voice

### ISSUE THREAD

**Issue by crisptrutski** [alda-lang/alda#76]
Perhaps there's already a convenience way to note this, or it's the job of some post-processing, but I'd like to be able have overlap between notes, eg. play a series of 8th notes all with a 4th note duration.

Examples would be for guitar or harp lines.

As far as I can tell, the only way to do this would be to have multiple voices and alternate between them, but it would be nice to just set the duration separately and write the notes serially.

**Comment by daveyarwood** [comment]
This would definitely be a useful feature.

I wonder if we could accomplish this by setting `quant` to a value higher than 100? Currently [there is an assertion](https://github.com/alda-lang/alda/blob/master/src/alda/lisp/attributes.clj#L10-L12) that the value for the `quant` attribute be between 0 and 100, but theoretically, if we removed the upper bound, the notes should still be the same duration (in that the next note will still start when it's supposed to), but it will "sound" longer.

We should try removing the upper bound on quantization values, and see if this works:

    piano: (quant 200) c8 d e f g

**Comment by crisptrutski** [comment]
Confirmed that `(quantization 300)` with some guitar melody I'm playing with now sounds 3 times as good :smile:

**Comment by daveyarwood** [comment]
Yes! :boom:
