### ISSUE TITLE
Strange parser issue with old REPL session

### ISSUE THREAD

**Issue by crisptrutski** [alda-lang/alda#77]
Left a REPL running overnight on OSX, came back to it after hibernating and found that it could no longer take input:

```
java.util.zip.ZipException: invalid distance too far back
                     java.util.zip.InflaterInputStream.read          InflaterInputStream.java:  164
                             java.io.FilterInputStream.read            FilterInputStream.java:  133
                          java.io.BufferedInputStream.read1          BufferedInputStream.java:  284
                           java.io.BufferedInputStream.read          BufferedInputStream.java:  345
                         sun.nio.cs.StreamDecoder.readBytes                StreamDecoder.java:  284
                          sun.nio.cs.StreamDecoder.implRead                StreamDecoder.java:  326
                              sun.nio.cs.StreamDecoder.read                StreamDecoder.java:  178
                             java.io.InputStreamReader.read            InputStreamReader.java:  184
                                java.io.BufferedReader.fill               BufferedReader.java:  161
                                java.io.BufferedReader.read               BufferedReader.java:  182
                                         clojure.core/slurp                          core.clj: 6654
                                 clojure.lang.RestFn.invoke                       RestFn.java:  410
                                     instaparse.core/parser                          core.clj:  223
...
```

Not sure if this is a JLine or Instaparse issue, or how easy to reproduce it is, but thought it worth noting.

**Comment by daveyarwood** [comment]
Weird! Let's keep this issue open -- it's definitely worth exploring, especially if we implement #49 and users might have Alda REPL servers running for long periods of time.

**Comment by daveyarwood** [comment]
After googling this error a little, this seems to be a JLine issue. It looks like it [comes up a lot with Minecraft servers](https://www.google.com/search?q=zipexception%20invalid%20distance%20too%20far%20back%20jline&rct=j), which also use JLine.

Not quite sure how to solve this at the moment, just taking notes.

**Comment by daveyarwood** [comment]
Whatever the cause of this issue was, I don't think it's relevant anymore in the current Alda ecosystem.

Now, the long-running process is not the Alda REPL, but the Alda server. The server does not use JLine, so I think we are in the clear!
