### ISSUE TITLE
BNF parser

### ISSUE THREAD

**Issue by ondras** [alda-lang/alda#78]
Hi,

I would love to parse your grammar (https://github.com/alda-lang/alda/blob/master/grammar/alda.bnf) using JavaScript, but I am not aware of any compatible with your BNF format. Can you suggest some?

The "omit node" angle brackets and regexp literals seem to be a little non-standard...

**Comment by crisptrutski** [comment]
I believe these extensions to EBNF are unique to instaparse, but you could use the CLJS port from JavaScript: https://github.com/lbradstreet/instaparse-cljs

**Comment by ondras** [comment]
Yay, thanks! Let me try that.

**Comment by daveyarwood** [comment]
@ondras It may also interest you to know that we are working on [an experimental ClojureScript fork of Alda](http://github.com/alda-lang/alda-cljs), which we are tracking in issue #72 

This fork uses Instaparse to parse the Alda grammar and return a nested JavaScript array, which you can use from vanilla JavaScript via an exported `alda_cljs.parser.parse` function. There is still work to be done (I just started this project last night), but hopefully it will be useful to you, even at this early stage.

Closing this issue for now, but feel free to join the conversation at #72 if you have any thoughts/questiosn - thanks!

**Comment by ondras** [comment]
Thanks a lot for your info! Already commented in #72.
