### ISSUE TITLE
#alda channel on Slack

### ISSUE THREAD

**Issue by pkobrien** [alda-lang/alda#86]
I created an #alda channel on Slack. Hope you like it. See you there.

**Comment by MadcapJake** [comment]
On which slack?

**Comment by crisptrutski** [comment]
[Clojurians](http://clojurians.net)

**Comment by daveyarwood** [comment]
Sweet! Good idea.

**Comment by crisptrutski** [comment]
Meant to just create a PR there, but forgot about my **absolute power**.

Also still wondering whether gitter or creating a dedicated slack community (see http://rauchg.com/slackin/) wouldn't be more approachable, flexible and future-proof

**Comment by MadcapJake** [comment]
A gitter would be nice but I think maybe a dedicated slack makes more sense than even the current Clojurian channel:
* (re: Gitter) Slack is a little more non-tech crowd friendly—no need for a github account.
* (re: current channel) In a perfect world all musicians would be clojurians, but I'm afraid that's not the case in ours :stuck_out_tongue_winking_eye: . 
* A dedicated slack means that Alda can be the focus, front-and-center on the first channel the users enter.  Slack may be more friendly to non-tech users than Gitter but it certainly isn't perfect.  There's a couple of steps left after registering and logging in before you're in the `#Alda` channel. 
* I don't know the details of Clojurians' Slack registration, but for free acounts, there is a limited number of messages. Perhaps the Clojurian users wouldn't want non-clojure users contributing against that limit.

**Comment by daveyarwood** [comment]
http://slack.alda.io <-- a thing now

:metal:
