### ISSUE TITLE
Notes with arbitrary pitches

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda#87]
As an alternative to a specific note within a specific octave (e.g. Bb5), we should be able to specify a precise frequency, in Hz.

Tentative syntax idea:

```
c4 (1000)1~2. (2000)4 (3000)1
```

This should help pave the way for plugins to provide syntax for microtonal music / alternate tunings (#45)

**Comment by crisptrutski** [comment]
How about `(tone 1000)` instead? Maybe it's silly, but I like these `(...)` forms all looking like s-expressions still, especially if alda get's to the point where you can start embedding clojure code it'll fit together better. We may even want to support walking and transforming those intermediate ASTs in plugins :haircut:

**Comment by daveyarwood** [comment]
That's not a bad idea. Maybe implementing embedded Clojure code should be the priority, and we can use that as a stepping-stone for building in new features that don't merit having their own syntax. It will start becoming harder and harder to come up with new syntax elements, the more we add, so leaning on embedded Clojure code will help with that problem as well.

We could make anything in the `alda.lisp` namespace available to embedded Clojure code, and then we could define things in `alda.lisp` that aren't available as first-class syntax elements in Alda. We could define a `hz` macro, maybe, that generates a note with an exact pitch in Hz, and a duration calculated from a note-duration string:

    c4 (hz 1000 "1~2.") (hz 2000 "4") (hz 3000 "1")

**Comment by daveyarwood** [comment]
Reserving parentheses for this in the Alda grammar would be pretty badass IMO. Currently the only thing using them is attribute-change events, but maybe we could hack in a way to re-implement those in terms of embedded Clojure code?

The alternative would be some new syntax for embedded Clojure code, like maybe `#(hz 1000)` (which is the same syntax that LilyPond uses for embedded Scheme)

**Comment by crisptrutski** [comment]
Don't see much difficulty with just reserving braces for clojure code, and having attribute functions/macros getting called directly. At the same time, I think it's cool to have an "eval free" mode where those S expressions are compiled by a basic alda interpreter - eg. to make sandboxing www.try-alda.com a sinch.

The main thing to watch out for as making sure that misuse of the main operators still results in quick and user friendly read-time errors, but that can be as simple as throwing exceptions.

For the `hz` function, I think we should still have an "implicit duration" arity - I like that you can have the same phrase played at a different meter when fragments and goto's land - certainly will save extra data transforms when writing that `bach-in-a-box` plugin.

If you do want to hash-things-up, not tempted to use `;` for comments?

**Comment by daveyarwood** [comment]
I feel like we've already committed to `#` at this point -- even though Alda is young and probably not used in "production" anywhere, I wouldn't want to break people's existing scores. I think I prefer `#` anyway -- I feel like it will be familiar as a comment delimiter to a wider range of people than `;`

I totally agree on the "implicit duration arity" thing -- it's such a simple thing, but can be used to make all sorts of interesting music!

**Comment by elyisgreat** [comment]
I mentioned this on Issue #45 , but I may as well bring it up here as well.
>I think the easiest way to express microtones is via MIDI numbers. You could have something like #m where # is the MIDI number of the note (this preserves the syntax for numbers after the note names). So 60.5m8 would be an eighth-note exactly between C4 and C#4. You could also have #q where q is the frequency in Hz, so 440.4q16 would be a 16th note with a frequency of 440.4Hz.

**Comment by daveyarwood** [comment]
Merged into https://github.com/alda-lang/alda-sound-engine-clj/issues/1, which combines #45 and this issue.
