### ISSUE TITLE
Implement advanced rhythms

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda#9]
**Cram**

I came up with this idea for representing advanced rhythms. I call it "cram" because you're basically cramming a bunch of notes inside of a set duration and dividing them up either evenly or according to a weight distribution. 

(**EDIT 9/7/15:** @crisptrutski has a much better idea -- see comments below)
Desired syntax:

    { d+ c+ < b }2 

The above is one way to represent a quarter note triplet -- it's 3 notes crammed into the space of a half note. By default, each note inside the braces is equal in length.

Notes inside of "cram brackets" use a slightly different syntax than usual, in that you don't specify exact note durations like eighth, quarter, etc. Instead, you can (optionally) specify how much weight each crammed note gets, by adding \*'s to the notes you want to be relatively longer than the others. This can get rather complicated, but here is an simple example:

    { c* d }4

The "c" has one \*, and the "d" has none, and they are crammed into the space of a quarter note (4). By default, a note has no \*, which corresponds to a ratio of 1:1 (i.e. all notes are equal in length). With each \* that you add, the first number of the ratio increases by one. So what this means is that in the example above, the "c" note (c*) has a length ratio of 2:1, whereas the "d" note (d) is just 1:1 (technically 1:2, compared to the "c" note). Because the "c" note is twice as long as the "d" note, and the two notes are crammed into the space of a quarter note, the result is two "swung" eighths, or in other words, an eighth note triplet where the "c" occupies the first two notes, and the "d" occupies the third.

Perhaps an easier way to think about adding \*'s to notes within cram brackets, is that with each \* you add, it's like adding another note into the crammed group, only instead of a new note, you're repeating the note you *'d, and then tying them together.

It should be possible to include rests and chords inside of cram brackets, too.

**Second/millisecond durations**

Come up with some syntax for overriding the beat/tempo model and letting users define exact durations of notes in seconds and milliseconds. Could be as simple as `c60s` (a C lasting 60 seconds), `d+500ms` (a D# lasting 500 milliseconds), etc.

**Comment by crisptrutski** [comment]
In case you haven't encountered it - Tidal has an interesting way of expressing rhythm: https://github.com/tidalcycles/Tidal/blob/master/doc/tidal.md#sequences. 

Not sure if the `{}` and `[]` notations for polyphony are useful when alda already has voices, but a shorthand for repetition and being able to nest these "time warps" is quite convenient. 

Regarding the suggested `*` syntax, that seems clunky, and in the worst-case more verbose and less readable. Is there an issue with using the regular syntax, and then scaling all note durations based on the `given duration of sequence / total of naive note durations in sequence`?

**Comment by 8dx** [comment]
I think that this format is actually extremely intuitive and functional, and I can't wait to put it to personal use.

**Comment by crisptrutski** [comment]
Hope that I didn't come across too forthright - more enthused than anything, this is exactly the kind of feature I'd like to use also (regardless the form)

To clear up what I'm saying about `*` as emphasis token, let me use too examples:

1. `{a2 b8 c d e16 f g}4` vs. `{e************ b* c* d* e f g}4` (don't make me count)
2. `{{e f g}* }4` (if we support nesting, do `cram`s need to support emphasis?)
3 `{a2 b*}` (is this illegal? what does that mean about calling recursively calling existing patterns in a `cram`?

Hence suggest that the usual notation applies, and *actual* lengths of notes are calculated by the obvious scaling, ie. `{a4 e1}4` would have durations of `1/20th`` and `1/5` of a bar respectively, to give the duration of a quarter note, ie. the same meaning as `{a16 e4}4` or `{a12 e 3}4`

**Comment by daveyarwood** [comment]
@crisptrutski I totally agree! I really like what you're proposing -- it's much more elegant than my idea, and probably more intuitive. So basically, we would add up the note values inside the curly braces to get a total note value, and determine each note's lion-share of the total time (the note value to the right of the close curly brace) by dividing it by the total note value. Makes perfect sense to me.

I also like the idea of nesting -- it would make it easier to represent really complex rhythms.

**Comment by daveyarwood** [comment]
Somewhat off-topic, but this paper is a really interesting read involving algorithmic polyrhythms: http://cgm.cs.mcgill.ca/~godfried/publications/banff.pdf

**Comment by crisptrutski** [comment]
Plan on fooling around with this something over the coming weekend :jack_o_lantern:

**Comment by daveyarwood** [comment]
:metal::jack_o_lantern::metal:

**Comment by crisptrutski** [comment]
OK, I'm cracking this open now!

First idea - use a macro to parse the notes inside the expression, but that fights against the "outside-in" resolution of macros. Next idea is to use `binding` to isolate changes to the main `*dynamic-vars*` in `alda.lisp` (and clear out the events), calculate the new events, scale their offsets and durations, and then reinject those events back into the root scope.

Simpler ideas welcome ^^,

**Comment by crisptrutski** [comment]
Oh, also going to reset the environment's duration to a quarter note in the rebinding also. Let me know if you disagree with this, or if I'm missing any other attributes that need special treatment

**Comment by crisptrutski** [comment]
RE: the grammer, I'm thinking we should only allow `events` inside the `{}` brackets - correct?

**Comment by daveyarwood** [comment]
> RE: the grammer, I'm thinking we should only allow events inside the {} brackets - correct?

Seems legit. We probably don't want to allow voice groups (which are not technically events) or switching instruments inside the brackets. Basically it's like *stretching the fabric of space-time around a portion of an instrument part's events* :milky_way: 

> Oh, also going to reset the environment's duration to a quarter note in the rebinding also. Let me know if you disagree with this, or if I'm missing any other attributes that need special treatment

That sounds OK to me! We can always patch it in the future if it ends up confusing people.

> OK, I'm cracking this open now!

> First idea - use a macro to parse the notes inside the expression, but that fights against the "outside-in" resolution of macros. Next idea is to use binding to isolate changes to the main *dynamic-vars* in alda.lisp (and clear out the events), calculate the new events, scale their offsets and durations, and then reinject those events back into the root scope.

> Simpler ideas welcome ^^,

I think the approach I would take is to add a new dynamic var like `*time-scale-factor*` or something, and use that in the calculation of durations. Then there could be a macro that binds `*time-scale-factor*` to a new value and evaluates the body within that context.

**Comment by crisptrutski** [comment]
@daveyarwood OK, that approach might not work, because `alter-var-root` refers to.. the root. Don't think we can imperatively mutates dynamic bindings

**Comment by crisptrutski** [comment]
Stretching time is appealing.. the issue is you still need to inspect the time taken before stretching. I guess you could eval with custom bindings, get the duration, then set the stretch-factor and eval again. That way you never nest the bindings and my current hurdle is solved.

Just seems inefficient, going to soldier on a little bit longer :bear:

**Comment by crisptrutski** [comment]
Hmm.. `push-thread-bindings` seems to be end of the line unless I code to the Java implementation. That won't be fun to port to CLJS :fearful:

**Comment by crisptrutski** [comment]
This is the part where I curse you for making `alda.lisp` global side effect based :P

**Comment by daveyarwood** [comment]
Thanks to @crisptrutski's awesome work, we're very close to having C.R.A.M. (we should totally adopt this backronym in the official docs!) implemented. :tophat: :star2: 

Thinking ahead a bit to the "exact second/millisecond durations" part of this issue, we could implement that as a new `alda.lisp` function called `exact-duration` or `duration-ms`, which acts like a simplified version of `duration` that just returns a map that has a `:duration-fn` key, e.g. `{:duration-fn (constantly 3000)}`. I'm still in favor of adding first-class Alda syntax for this feature, as well, e.g. `c60s` (60 seconds), `d+500ms` (500 milliseconds)

**Comment by crisptrutski** [comment]
OK, will see about adding that last part tonight. When it comes to "memory" of notes, that is based around beats at the moment, so it might be worth refactoring slightly so that the the duration state can be beat OR duration based, so that tempo changes interact as expected with both kinds of persistence.

Naming wise I'll go with `duration-ms` - `exact-duration` makes `duration` sound a bit too sloppy :wink:

**Comment by daveyarwood** [comment]
When I have a chance, I might take a look at trying to simplify the way CRAM is implemented -- it's  pretty snappy for me when running small snippets in the REPL, but evaluating `multi-poly.alda` takes a while, which makes me wonder if there are performance issues due to the whole "dry run, then rollback" thing.

**Comment by crisptrutski** [comment]
Definitely super slow - added that file as a benchmark intentionally, those nested crams are exponentially expensive. No argument that dry run sucks :smile: 

Got pretty close to getting it working without in first attempt, but will need either code-walking macros or refactoring of `alda.lisp`. Of those I prefer the second :smile:

**Comment by daveyarwood** [comment]
(Reopening this until the "exact seconds/millisecond durations" feature is implemented)

**Comment by daveyarwood** [comment]
Working on second/millisecond durations now. I've decided to take a more flexible approach, creating an alternative to `note-length` instead of an alternative to `duration`.

e.g.:

    # alda syntax
    2000ms

    # parses into
    (duration (ms 2000))

The nice thing about this is that it creates the possibility of combining note-lengths (which represent a number of beats and are used in the context of the current tempo to calculate the length of the note in ms) with exact second/millisecond durations:

    # alda syntax
    4~2000ms

    # parses into
    (duration (note-length 4) (ms 2000))

The above duration == however long a quarter note is at the current tempo, plus 2000 ms.
