### ISSUE TITLE
Why does the "duration" attribute default to 1?

### ISSUE THREAD

**Issue by ondras** [alda-lang/alda#93]
This is not really an **issue**, just a question. The `duration` attribute defaults to 1 (https://github.com/alda-lang/alda/blob/master/src/alda/lisp/attributes.clj#L24), because the unit is one beat.

The AST, however, uses fractional duration units, one beat being represented as `4`. Perhaps these units shall be the same, for the sake of consistency?

**Comment by daveyarwood** [comment]
I think I was setting up a distinction between *note-length* and *duration*, where the note-length is the "fractional duration unit," i.e. 4 is a quarter note (1/4), and duration is the length of a note in beats. A duration can involve multiple note-lengths tied together, and dots. For example, `2~2.` is two note-lengths, `2` and `2.`, tied together, and the duration is 5 beats.

**Comment by ondras** [comment]
Hmm, duration with a dot, something my JS processor probably does not understand yet...

Anyway, @daveyarwood, thanks for explanation. I will use the value of 1/4 in my default `duration`, diverging from the Clojure impl.
