### ISSUE TITLE
Inline Clojure code

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda#94]
This feature idea has come up for discussion in various other issues, where it became apparent that we could actually implement other features in terms of inline Clojure code. Example: #87 

Quoting myself from that issue:

> Reserving parentheses for this in the Alda grammar would be pretty badass IMO. Currently the only thing using them is attribute-change events, but maybe we could hack in a way to re-implement those in terms of embedded Clojure code?

Moving toward doing as many things as possible with inline, embedded Clojure code would carry the benefit of not polluting the syntax of Alda with too many different symbols. For backwards compatibility, we should keep the symbols we have (e.g. `%marker`, `@at-marker`), but with inline Clojure code, we should also be able to use these features via the alda.lisp namespace, i.e. `(marker "foo")`, `(at-marker "bar")`, which some users might even prefer. We'll just make sure that we document that these things can be done in more than one way.

I think the set of symbols that we're currently using are for common-enough tasks that it makes sense that they also get the privilege of having their own first-class syntax in the Alda grammar, but as we add new features to Alda (microtonal music, etc.), it will only get harder and harder to find symbols that we haven't used yet, so I think this is a step in the right direction.

---

EDIT: 
Checklist:

- [x] Grammar/parser changes: read anything between parens as a Clojure expression
- [x] Transform Clojure expressions like `[:clj-expr "(+ 1 1)"]` into i.e. `'(+ 1 1)`
- [x] macroexpand commas and semicolons into separate expressions, i.e. `(volume 50, quant 50)` becomes `(do (volume 50) (quant 50))`
    - [x] commas/semicolons can exist in strings...
    - [x] ...and character literals (`\,` and `\;`)
- [x] Custom namespace resolution -- try to resolve in the context of alda.lisp first, and if that fails, evaluate in the current namespace at runtime (whatever that is)
- [x] Make sure `defattribute` is doing all the things we need it to do.
    - [x] Define bang-suffixed versions of the setter fns that do a global attribute change.
    - [x] Make sure it defines setter functions for all aliases of the function -- I don't think it does.

**Comment by daveyarwood** [comment]
We could implement this using [clojail](https://github.com/Raynes/clojail), maybe. Hopefully it is possible to evaluate expressions within the context of the `alda.lisp` namespace, so that people can do `(marker "bar")` instead of `(alda.lisp/marker "bar")`

**Comment by daveyarwood** [comment]
Re-implementing attribute-change events in terms of inline Clojure code will be interesting... we'll want to preserve the ability to change multiple attributes at once, separating them by commas or semicolons, e.g.

    (volume 50, tempo! 90)
    (volume 50; tempo! 90)

Since commas are treated as whitespace in Clojure code anyway, and since semicolons are used for comments and not typically seen in the middle of an S-expression, maybe we could do a macroexpansion on every inline Clojure code before evaluating it, i.e.:

    (volume 50, tempo! 90) => (do (volume 50) (tempo! 90))

**Comment by crisptrutski** [comment]
Lisp Can Do It :+1: :palm_tree:

**Comment by daveyarwood** [comment]
This will also involve changing the syntax for long comments, which is currently `(*  this   *)`

We *could* write the grammar in such a way that will read `(* this *)` as a long comment, and `(anything else between parentheses)` as a Clojure expression, but I think for the sake of clarity we should just change the long comment syntax, or perhaps remove it altogether.

One idea that I'm kinda leaning towards is using `(comment "Clojure's comment macro")` as the official long comment syntax in Alda.

**Comment by crisptrutski** [comment]
So `(* this *)` looks like a really scary face, so totally OK with the change. 

The implicit split-and-`do`-hoisting on `,` or `;`  in the top level form is a bit weird, but don't have a better suggestion besides `(volume 50) (tempo! 90)`

**Comment by daveyarwood** [comment]
I'm starting to work on this on a branch -- I think once we get inline Clojure code working, we can probably crush a few of the other features pretty easily by just defining things in the alda.lisp namespace! :guitar: :notes:

**Comment by daveyarwood** [comment]
Oh man, I'm almost done now. This is gonna be awesome.
